<?php
function CardName ($cardID, $showPitch=true)
{
    $arr = str_split($cardID, 3);
    $set = $arr[0];
    $num = $arr[1];
    

if ($set == "ARC")
	{  switch($num)	   {

		case "000": if ($showPitch == false) return "Eye of Ophidia";
			else return "Eye of Ophidia (blue)";
		case "001": if ($showPitch == false) return "Dash, Inventor Extraordinaire";
			else return "Dash, Inventor Extraordinaire (None)";
		case "002": if ($showPitch == false) return "Dash";
			else return "Dash (None)";
		case "003": if ($showPitch == false) return "‘Teklo Plasma Pistol";
			else return "‘Teklo Plasma Pistol (None)";
		case "004": if ($showPitch == false) return "Teklo Foundry Heart";
			else return "Teklo Foundry Heart (None)";
		case "005": if ($showPitch == false) return "Achilles Accelerator";
			else return "Achilles Accelerator (None)";
		case "006": if ($showPitch == false) return "High Octane";
			else return "High Octane (red)";
		case "007": if ($showPitch == false) return "Teklo Core";
			else return "Teklo Core (blue)";
		case "008": if ($showPitch == false) return "Maximum Velocity";
			else return "Maximum Velocity (red)";
		case "009": if ($showPitch == false) return "Spark of Genius";
			else return "Spark of Genius (yellow)";
		case "010": if ($showPitch == false) return "Induction Chamber";
			else return "Induction Chamber (red)";
		case "011": if ($showPitch == false) return "Pedal to the Metal";
			else return "Pedal to the Metal (red)";
		case "012": if ($showPitch == false) return "Pedal to the Metal";
			else return "Pedal to the Metal (yellow)";
		case "013": if ($showPitch == false) return "Pedal to the Metal";
			else return "Pedal to the Metal (blue)";
		case "014": if ($showPitch == false) return "Pour the Mold";
			else return "Pour the Mold (red)";
		case "015": if ($showPitch == false) return "Pour the Mold";
			else return "Pour the Mold (yellow)";
		case "016": if ($showPitch == false) return "Pour the Mold";
			else return "Pour the Mold (blue)";
		case "017": if ($showPitch == false) return "Aether Sink";
			else return "Aether Sink (yellow)";
		case "018": if ($showPitch == false) return "Cognition Nodes";
			else return "Cognition Nodes (blue)";
		case "019": if ($showPitch == false) return "Convection Amplifier";
			else return "Convection Amplifier (red)";
		case "020": if ($showPitch == false) return "Qver Loop";
			else return "Qver Loop (red)";
		case "021": if ($showPitch == false) return "Qver Loop";
			else return "Qver Loop (yellow)";
		case "022": if ($showPitch == false) return "Qver Loop";
			else return "Qver Loop (blue)";
		case "023": if ($showPitch == false) return "Throttle";
			else return "Throttle (red)";
		case "024": if ($showPitch == false) return "Throttle";
			else return "Throttle (yellow)";
		case "025": if ($showPitch == false) return "Throttle";
			else return "Throttle (blue)";
		case "026": if ($showPitch == false) return "Zero to Sixty";
			else return "Zero to Sixty (red)";
		case "027": if ($showPitch == false) return "Zero to Sixty";
			else return "Zero to Sixty (yellow)";
		case "028": if ($showPitch == false) return "Zero to Sixty";
			else return "Zero to Sixty (blue)";
		case "029": if ($showPitch == false) return "Zipper Hit";
			else return "Zipper Hit (red)";
		case "030": if ($showPitch == false) return "Zipper Hit";
			else return "Zipper Hit (yellow)";
		case "031": if ($showPitch == false) return "Zipper Hit";
			else return "Zipper Hit (blue)";
		case "032": if ($showPitch == false) return "Locked and Loaded";
			else return "Locked and Loaded (red)";
		case "033": if ($showPitch == false) return "Locked and Loaded";
			else return "Locked and Loaded (yellow)";
		case "034": if ($showPitch == false) return "Locked and Loaded";
			else return "Locked and Loaded (blue)";
		case "035": if ($showPitch == false) return "Dissipation Shield";
			else return "Dissipation Shield (yellow)";
		case "036": if ($showPitch == false) return "Hyper Driver";
			else return "Hyper Driver (red)";
		case "037": if ($showPitch == false) return "Optekal Monocle";
			else return "Optekal Monocle (blue)";
		case "038": if ($showPitch == false) return "Azalea, Ace in the Hole";
			else return "Azalea, Ace in the Hole (None)";
		case "039": if ($showPitch == false) return "£ Azalea o";
			else return "£ Azalea o (None)";
		case "040": if ($showPitch == false) return "Death Dealer";
			else return "Death Dealer (None)";
		case "041": if ($showPitch == false) return "Skullbone Crosswrap";
			else return "Skullbone Crosswrap (None)";
		case "042": if ($showPitch == false) return "Bull's Eye Bracers";
			else return "Bull's Eye Bracers (None)";
		case "043": if ($showPitch == false) return "Red in the Ledger";
			else return "Red in the Ledger (red)";
		case "044": if ($showPitch == false) return "Three of a Kind";
			else return "Three of a Kind (red)";
		case "045": if ($showPitch == false) return "Endless Arrow";
			else return "Endless Arrow (red)";
		case "046": if ($showPitch == false) return "Nock the Deathwhistle";
			else return "Nock the Deathwhistle (blue)";
		case "047": if ($showPitch == false) return "Rapid Fire";
			else return "Rapid Fire (yellow)";
		case "048": if ($showPitch == false) return "Take Cover";
			else return "Take Cover (red)";
		case "049": if ($showPitch == false) return "Take Cover";
			else return "Take Cover (yellow)";
		case "050": if ($showPitch == false) return "Take Cover";
			else return "Take Cover (blue)";
		case "051": if ($showPitch == false) return "Silver the Tip";
			else return "Silver the Tip (red)";
		case "052": if ($showPitch == false) return "Silver the Tip";
			else return "Silver the Tip (yellow)";
		case "053": if ($showPitch == false) return "Silver the Tip";
			else return "Silver the Tip (blue)";
		case "054": if ($showPitch == false) return "Take Aim";
			else return "Take Aim (red)";
		case "055": if ($showPitch == false) return "Take Aim";
			else return "Take Aim (yellow)";
		case "056": if ($showPitch == false) return "Take Aim";
			else return "Take Aim (blue)";
		case "057": if ($showPitch == false) return "Head Shot";
			else return "Head Shot (red)";
		case "058": if ($showPitch == false) return "Head Shot";
			else return "Head Shot (yellow)";
		case "059": if ($showPitch == false) return "Head Shot";
			else return "Head Shot (blue)";
		case "060": if ($showPitch == false) return "Hamstring Shot";
			else return "Hamstring Shot (red)";
		case "061": if ($showPitch == false) return "Hamstring Shot";
			else return "Hamstring Shot (yellow)";
		case "062": if ($showPitch == false) return "Hamstring Shot";
			else return "Hamstring Shot (blue)";
		case "063": if ($showPitch == false) return "Ridge Rider Shot";
			else return "Ridge Rider Shot (red)";
		case "064": if ($showPitch == false) return "Ridge Rider Shot";
			else return "Ridge Rider Shot (yellow)";
		case "065": if ($showPitch == false) return "Ridge Rider Shot";
			else return "Ridge Rider Shot (blue)";
		case "066": if ($showPitch == false) return "Salvage Shot";
			else return "Salvage Shot (red)";
		case "067": if ($showPitch == false) return "Salvage Shot";
			else return "Salvage Shot (yellow)";
		case "068": if ($showPitch == false) return "Salvage Shot";
			else return "Salvage Shot (blue)";
		case "069": if ($showPitch == false) return "Searing Shot";
			else return "Searing Shot (red)";
		case "070": if ($showPitch == false) return "Searing Shot";
			else return "Searing Shot (yellow)";
		case "071": if ($showPitch == false) return "Searing Shot";
			else return "Searing Shot (blue)";
		case "072": if ($showPitch == false) return "Sic 'Em Shot";
			else return "Sic 'Em Shot (red)";
		case "073": if ($showPitch == false) return "Sic 'Em Shot";
			else return "Sic 'Em Shot (yellow)";
		case "074": if ($showPitch == false) return "Sic 'Em Shot";
			else return "Sic 'Em Shot (blue)";
		case "075": if ($showPitch == false) return "Viserai, Rune Blood";
			else return "Viserai, Rune Blood (None)";
		case "076": if ($showPitch == false) return "Viserai";
			else return "Viserai (None)";
		case "077": if ($showPitch == false) return "Nebula Blade";
			else return "Nebula Blade (None)";
		case "078": if ($showPitch == false) return "Grasp of the Arknight";
			else return "Grasp of the Arknight (None)";
		case "079": if ($showPitch == false) return "Crown of Dichotomy";
			else return "Crown of Dichotomy (None)";
		case "080": if ($showPitch == false) return "Arknight Ascendancy";
			else return "Arknight Ascendancy (red)";
		case "081": if ($showPitch == false) return "Mordred Tide";
			else return "Mordred Tide (red)";
		case "082": if ($showPitch == false) return "Ninth Blade of the Blood Oatt";
			else return "Ninth Blade of the Blood Oatt (yellow)";
		case "083": if ($showPitch == false) return "Become the Arknight";
			else return "Become the Arknight (blue)";
		case "084": if ($showPitch == false) return "Tome of the Arknight";
			else return "Tome of the Arknight (blue)";
		case "085": if ($showPitch == false) return "Spellblade Assault";
			else return "Spellblade Assault (red)";
		case "086": if ($showPitch == false) return "Spellblade Assault";
			else return "Spellblade Assault (yellow)";
		case "087": if ($showPitch == false) return "Spellblade Assault";
			else return "Spellblade Assault (blue)";
		case "088": if ($showPitch == false) return "Reduce to Runechant";
			else return "Reduce to Runechant (red)";
		case "089": if ($showPitch == false) return "Reduce to Runechant";
			else return "Reduce to Runechant (yellow)";
		case "090": if ($showPitch == false) return "Reduce to Runechant";
			else return "Reduce to Runechant (blue)";
		case "091": if ($showPitch == false) return "Qath of the Arknight";
			else return "Qath of the Arknight (red)";
		case "092": if ($showPitch == false) return "Qath of the Arknight";
			else return "Qath of the Arknight (yellow)";
		case "093": if ($showPitch == false) return "Qath of the Arknight";
			else return "Qath of the Arknight (blue)";
		case "094": if ($showPitch == false) return "Amplify the Arknight";
			else return "Amplify the Arknight (red)";
		case "095": if ($showPitch == false) return "Amplify the Arknight";
			else return "Amplify the Arknight (yellow)";
		case "096": if ($showPitch == false) return "Amplify the Arknight";
			else return "Amplify the Arknight (blue)";
		case "097": if ($showPitch == false) return "Drawn to the Dark Dimension";
			else return "Drawn to the Dark Dimension (red)";
		case "098": if ($showPitch == false) return "Drawn to the Dark Dimension";
			else return "Drawn to the Dark Dimension (yellow)";
		case "099": if ($showPitch == false) return "Drawn to the Dark Dimension";
			else return "Drawn to the Dark Dimension (blue)";
		case "100": if ($showPitch == false) return "Rune Flash";
			else return "Rune Flash (red)";
		case "101": if ($showPitch == false) return "Rune Flash";
			else return "Rune Flash (yellow)";
		case "102": if ($showPitch == false) return "Rune Flash";
			else return "Rune Flash (blue)";
		case "103": if ($showPitch == false) return "Spellblade Strike";
			else return "Spellblade Strike (red)";
		case "104": if ($showPitch == false) return "Spellblade Strike";
			else return "Spellblade Strike (yellow)";
		case "105": if ($showPitch == false) return "Spellblade Strike";
			else return "Spellblade Strike (blue)";
		case "106": if ($showPitch == false) return "Bloodspill Invocation";
			else return "Bloodspill Invocation (red)";
		case "107": if ($showPitch == false) return "Bloodspill Invocation";
			else return "Bloodspill Invocation (yellow)";
		case "108": if ($showPitch == false) return "Bloodspill Invocation";
			else return "Bloodspill Invocation (blue)";
		case "109": if ($showPitch == false) return "Read the Runes";
			else return "Read the Runes (red)";
		case "110": if ($showPitch == false) return "Read the Runes";
			else return "Read the Runes (yellow)";
		case "111": if ($showPitch == false) return "Read the Runes";
			else return "Read the Runes (blue)";
		case "112": if ($showPitch == false) return "Runechant";
			else return "Runechant (None)";
		case "113": if ($showPitch == false) return "Cano, Dracai of Aether";
			else return "Cano, Dracai of Aether (None)";
		case "114": if ($showPitch == false) return "Kano";
			else return "Kano (None)";
		case "115": if ($showPitch == false) return "rucible of Aetherweav";
			else return "rucible of Aetherweav (None)";
		case "116": if ($showPitch == false) return "Storm Striders";
			else return "Storm Striders (None)";
		case "117": if ($showPitch == false) return "Robe of Rapture";
			else return "Robe of Rapture (None)";
		case "118": if ($showPitch == false) return "~ Blazing Aether";
			else return "~ Blazing Aether (red)";
		case "119": if ($showPitch == false) return "Sonic Boom";
			else return "Sonic Boom (yellow)";
		case "120": if ($showPitch == false) return "Forked Lightning";
			else return "Forked Lightning (red)";
		case "121": if ($showPitch == false) return "Lesson in Lava";
			else return "Lesson in Lava (yellow)";
		case "122": if ($showPitch == false) return "Tome of Aetherwind";
			else return "Tome of Aetherwind (red)";
		case "123": if ($showPitch == false) return "Absorb in Aether";
			else return "Absorb in Aether (red)";
		case "124": if ($showPitch == false) return "Absorb in Aether";
			else return "Absorb in Aether (yellow)";
		case "125": if ($showPitch == false) return "Absorb in Aether";
			else return "Absorb in Aether (blue)";
		case "126": if ($showPitch == false) return "Aether Spindle";
			else return "Aether Spindle (red)";
		case "127": if ($showPitch == false) return "Aether Spindle";
			else return "Aether Spindle (yellow)";
		case "128": if ($showPitch == false) return "Aether Spindle";
			else return "Aether Spindle (blue)";
		case "129": if ($showPitch == false) return "Stir the Aetherwinds";
			else return "Stir the Aetherwinds (red)";
		case "130": if ($showPitch == false) return "Stir the Aetherwinds";
			else return "Stir the Aetherwinds (yellow)";
		case "131": if ($showPitch == false) return "Stir the Aetherwinds";
			else return "Stir the Aetherwinds (blue)";
		case "132": if ($showPitch == false) return "Aether Flare";
			else return "Aether Flare (red)";
		case "133": if ($showPitch == false) return "Aether Flare";
			else return "Aether Flare (yellow)";
		case "134": if ($showPitch == false) return "Aether Flare";
			else return "Aether Flare (blue)";
		case "135": if ($showPitch == false) return "Index";
			else return "Index (red)";
		case "136": if ($showPitch == false) return "Index";
			else return "Index (yellow)";
		case "137": if ($showPitch == false) return "Index";
			else return "Index (blue)";
		case "138": if ($showPitch == false) return "Reverberate";
			else return "Reverberate (red)";
		case "139": if ($showPitch == false) return "Reverberate";
			else return "Reverberate (yellow)";
		case "140": if ($showPitch == false) return "Reverberate";
			else return "Reverberate (blue)";
		case "141": if ($showPitch == false) return "Scalding Rain";
			else return "Scalding Rain (red)";
		case "142": if ($showPitch == false) return "Scalding Rain";
			else return "Scalding Rain (yellow)";
		case "143": if ($showPitch == false) return "Scalding Rain";
			else return "Scalding Rain (blue)";
		case "144": if ($showPitch == false) return "Zap";
			else return "Zap (red)";
		case "145": if ($showPitch == false) return "Zap";
			else return "Zap (yellow)";
		case "146": if ($showPitch == false) return "Zap";
			else return "Zap (blue)";
		case "147": if ($showPitch == false) return "Voltic Bolt";
			else return "Voltic Bolt (red)";
		case "148": if ($showPitch == false) return "Voltic Bolt";
			else return "Voltic Bolt (yellow)";
		case "149": if ($showPitch == false) return "Voltic Bolt";
			else return "Voltic Bolt (blue)";
		case "150": if ($showPitch == false) return "Arcanite Skullcap";
			else return "Arcanite Skullcap (None)";
		case "151": if ($showPitch == false) return "Talismanic Lens";
			else return "Talismanic Lens (None)";
		case "152": if ($showPitch == false) return "Vest of the First Fist";
			else return "Vest of the First Fist (None)";
		case "153": if ($showPitch == false) return "Bracers of Beliet";
			else return "Bracers of Beliet (None)";
		case "154": if ($showPitch == false) return "Mage Master Boots";
			else return "Mage Master Boots (None)";
		case "155": if ($showPitch == false) return "Nullrune Hood";
			else return "Nullrune Hood (None)";
		case "156": if ($showPitch == false) return "Nullrune Robe";
			else return "Nullrune Robe (None)";
		case "157": if ($showPitch == false) return "Nullrune Gloves";
			else return "Nullrune Gloves (None)";
		case "158": if ($showPitch == false) return "Nullrune Boots";
			else return "Nullrune Boots (None)";
		case "159": if ($showPitch == false) return "Command and Conquer";
			else return "Command and Conquer (red)";
		case "160": if ($showPitch == false) return "Art of War";
			else return "Art of War (yellow)";
		case "161": if ($showPitch == false) return "Pursuit of Knowledge";
			else return "Pursuit of Knowledge (blue)";
		case "162": if ($showPitch == false) return "Chains of Eminence";
			else return "Chains of Eminence (red)";
		case "163": if ($showPitch == false) return "Rusted Relic";
			else return "Rusted Relic (blue)";
		case "164": if ($showPitch == false) return "Life for a Life";
			else return "Life for a Life (red)";
		case "165": if ($showPitch == false) return "Life for a Life";
			else return "Life for a Life (yellow)";
		case "166": if ($showPitch == false) return "Life for a Life";
			else return "Life for a Life (blue)";
		case "167": if ($showPitch == false) return "Enchanting Melody";
			else return "Enchanting Melody (red)";
		case "168": if ($showPitch == false) return "Enchanting Melody";
			else return "Enchanting Melody (yellow)";
		case "169": if ($showPitch == false) return "Enchanting Melody";
			else return "Enchanting Melody (blue)";
		case "170": if ($showPitch == false) return "Plunder Run";
			else return "Plunder Run (red)";
		case "171": if ($showPitch == false) return "Plunder Run";
			else return "Plunder Run (yellow)";
		case "172": if ($showPitch == false) return "Plunder Run";
			else return "Plunder Run (blue)";
		case "173": if ($showPitch == false) return "Eirina's Prayer";
			else return "Eirina's Prayer (red)";
		case "174": if ($showPitch == false) return "Eirina's Prayer";
			else return "Eirina's Prayer (yellow)";
		case "175": if ($showPitch == false) return "Eirina's Prayer";
			else return "Eirina's Prayer (blue)";
		case "176": if ($showPitch == false) return "Back Alley Breakline";
			else return "Back Alley Breakline (red)";
		case "177": if ($showPitch == false) return "Back Alley Breakline";
			else return "Back Alley Breakline (yellow)";
		case "178": if ($showPitch == false) return "Back Alley Breakline";
			else return "Back Alley Breakline (blue)";
		case "179": if ($showPitch == false) return "Cadaverous Contraband";
			else return "Cadaverous Contraband (red)";
		case "180": if ($showPitch == false) return "Cadaverous Contraband";
			else return "Cadaverous Contraband (yellow)";
		case "181": if ($showPitch == false) return "Cadaverous Contraband";
			else return "Cadaverous Contraband (blue)";
		case "182": if ($showPitch == false) return "Fervent Forerunner";
			else return "Fervent Forerunner (red)";
		case "183": if ($showPitch == false) return "Fervent Forerunner";
			else return "Fervent Forerunner (yellow)";
		case "184": if ($showPitch == false) return "Fervent Forerunner";
			else return "Fervent Forerunner (blue)";
		case "185": if ($showPitch == false) return "Moon Wish";
			else return "Moon Wish (red)";
		case "186": if ($showPitch == false) return "Moon Wish";
			else return "Moon Wish (yellow)";
		case "187": if ($showPitch == false) return "Moon Wish";
			else return "Moon Wish (blue)";
		case "188": if ($showPitch == false) return "Push the Point";
			else return "Push the Point (red)";
		case "189": if ($showPitch == false) return "Push the Point";
			else return "Push the Point (yellow)";
		case "190": if ($showPitch == false) return "Push the Point";
			else return "Push the Point (blue)";
		case "191": if ($showPitch == false) return "Ravenous Rabble";
			else return "Ravenous Rabble (red)";
		case "192": if ($showPitch == false) return "Ravenous Rabble";
			else return "Ravenous Rabble (yellow)";
		case "193": if ($showPitch == false) return "Ravenous Rabble";
			else return "Ravenous Rabble (blue)";
		case "194": if ($showPitch == false) return "Rifting";
			else return "Rifting (red)";
		case "195": if ($showPitch == false) return "Rifting";
			else return "Rifting (yellow)";
		case "196": if ($showPitch == false) return "Rifting";
			else return "Rifting (blue)";
		case "197": if ($showPitch == false) return "Vigor Rush";
			else return "Vigor Rush (red)";
		case "198": if ($showPitch == false) return "Vigor Rush";
			else return "Vigor Rush (yellow)";
		case "199": if ($showPitch == false) return "Vigor Rush";
			else return "Vigor Rush (blue)";
		case "200": if ($showPitch == false) return "Fate Foreseen";
			else return "Fate Foreseen (red)";
		case "201": if ($showPitch == false) return "Fate Foreseen";
			else return "Fate Foreseen (yellow)";
		case "202": if ($showPitch == false) return "Fate Foreseen";
			else return "Fate Foreseen (blue)";
		case "203": if ($showPitch == false) return "Come to Fight";
			else return "Come to Fight (red)";
		case "204": if ($showPitch == false) return "Come to Fight";
			else return "Come to Fight (yellow)";
		case "205": if ($showPitch == false) return "Come to Fight";
			else return "Come to Fight (blue)";
		case "206": if ($showPitch == false) return "Force Sight";
			else return "Force Sight (red)";
		case "207": if ($showPitch == false) return "Force Sight";
			else return "Force Sight (yellow)";
		case "208": if ($showPitch == false) return "Force Sight";
			else return "Force Sight (blue)";
		case "209": if ($showPitch == false) return "Lead the Charge";
			else return "Lead the Charge (red)";
		case "210": if ($showPitch == false) return "Lead the Charge";
			else return "Lead the Charge (yellow)";
		case "211": if ($showPitch == false) return "Lead the Charge";
			else return "Lead the Charge (blue)";
		case "212": if ($showPitch == false) return "Sun Kiss";
			else return "Sun Kiss (red)";
		case "213": if ($showPitch == false) return "Sun Kiss";
			else return "Sun Kiss (yellow)";
		case "214": if ($showPitch == false) return "Sun Kiss";
			else return "Sun Kiss (blue)";
		case "215": if ($showPitch == false) return "Whisper of the Oracle";
			else return "Whisper of the Oracle (red)";
		case "216": if ($showPitch == false) return "Whisper of the Oracle";
			else return "Whisper of the Oracle (yellow)";
		case "217": if ($showPitch == false) return "Whisper of the Oracle";
			else return "Whisper of the Oracle (blue)";
		case "218": if ($showPitch == false) return "Cracked Bauble";
			else return "Cracked Bauble (yellow)";

		   }	}
if ($set == "CRU")
	{  switch($num)	   {

		case "000": if ($showPitch == false) return "Arknight Shard";
			else return "Arknight Shard (blue)";
		case "001": if ($showPitch == false) return "vinar, Reckless Rampa;";
			else return "vinar, Reckless Rampa; (None)";
		case "002": if ($showPitch == false) return "Kayo, Berserker Runt";
			else return "Kayo, Berserker Runt (None)";
		case "003": if ($showPitch == false) return "Romping Club";
			else return "Romping Club (None)";
		case "004": if ($showPitch == false) return "Mandible Claw";
			else return "Mandible Claw (None)";
		case "005": if ($showPitch == false) return "Mandible Claw";
			else return "Mandible Claw (None)";
		case "006": if ($showPitch == false) return "Skullhorn";
			else return "Skullhorn (None)";
		case "007": if ($showPitch == false) return "Beast Within";
			else return "Beast Within (yellow)";
		case "008": if ($showPitch == false) return "Massacre";
			else return "Massacre (red)";
		case "009": if ($showPitch == false) return "Argh... Smash!";
			else return "Argh... Smash! (yellow)";
		case "010": if ($showPitch == false) return "Barraging Big Horn";
			else return "Barraging Big Horn (red)";
		case "011": if ($showPitch == false) return "Barraging Big Horn";
			else return "Barraging Big Horn (yellow)";
		case "012": if ($showPitch == false) return "Barraging Big Horn";
			else return "Barraging Big Horn (blue)";
		case "013": if ($showPitch == false) return "Predatory Assault";
			else return "Predatory Assault (red)";
		case "014": if ($showPitch == false) return "Predatory Assault";
			else return "Predatory Assault (yellow)";
		case "015": if ($showPitch == false) return "Predatory Assault";
			else return "Predatory Assault (blue)";
		case "016": if ($showPitch == false) return "Riled Up";
			else return "Riled Up (red)";
		case "017": if ($showPitch == false) return "Riled Up";
			else return "Riled Up (yellow)";
		case "018": if ($showPitch == false) return "Riled Up";
			else return "Riled Up (blue)";
		case "019": if ($showPitch == false) return "Swing Fist, Think Later";
			else return "Swing Fist, Think Later (red)";
		case "020": if ($showPitch == false) return "Swing Fist, Think Later";
			else return "Swing Fist, Think Later (yellow)";
		case "021": if ($showPitch == false) return "Swing Fist, Think Later";
			else return "Swing Fist, Think Later (blue)";
		case "022": if ($showPitch == false) return "Bravo, Showstopper";
			else return "Bravo, Showstopper (None)";
		case "023": if ($showPitch == false) return "Anothos";
			else return "Anothos (None)";
		case "024": if ($showPitch == false) return "Sledge of Anvilheim";
			else return "Sledge of Anvilheim (None)";
		case "025": if ($showPitch == false) return "Crater Fist";
			else return "Crater Fist (None)";
		case "026": if ($showPitch == false) return "Mangle";
			else return "Mangle (red)";
		case "027": if ($showPitch == false) return "Righteous Cleansing";
			else return "Righteous Cleansing (yellow)";
		case "028": if ($showPitch == false) return "Stamp Authority";
			else return "Stamp Authority (blue)";
		case "029": if ($showPitch == false) return "Towering Titan";
			else return "Towering Titan (red)";
		case "030": if ($showPitch == false) return "Towering Titan";
			else return "Towering Titan (yellow)";
		case "031": if ($showPitch == false) return "Towering Titan";
			else return "Towering Titan (blue)";
		case "032": if ($showPitch == false) return "Crush the Weak";
			else return "Crush the Weak (red)";
		case "033": if ($showPitch == false) return "Crush the Weak";
			else return "Crush the Weak (yellow)";
		case "034": if ($showPitch == false) return "Crush the Weak";
			else return "Crush the Weak (blue)";
		case "035": if ($showPitch == false) return "Chokeslam";
			else return "Chokeslam (red)";
		case "036": if ($showPitch == false) return "Chokeslam";
			else return "Chokeslam (yellow)";
		case "037": if ($showPitch == false) return "Chokeslam";
			else return "Chokeslam (blue)";
		case "038": if ($showPitch == false) return "Emerging Dominance";
			else return "Emerging Dominance (red)";
		case "039": if ($showPitch == false) return "Emerging Dominance";
			else return "Emerging Dominance (yellow)";
		case "040": if ($showPitch == false) return "Emerging Dominance";
			else return "Emerging Dominance (blue)";
		case "041": if ($showPitch == false) return "Blessing of Serenity";
			else return "Blessing of Serenity (red)";
		case "042": if ($showPitch == false) return "Blessing of Serenity";
			else return "Blessing of Serenity (yellow)";
		case "043": if ($showPitch == false) return "Blessing of Serenity";
			else return "Blessing of Serenity (blue)";
		case "044": if ($showPitch == false) return "Seismic Surge";
			else return "Seismic Surge (None)";
		case "045": if ($showPitch == false) return "Katsu, the Wanderer";
			else return "Katsu, the Wanderer (None)";
		case "046": if ($showPitch == false) return "Ira, Crimson Haze";
			else return "Ira, Crimson Haze (None)";
		case "047": if ($showPitch == false) return "enji, the Piercing Win";
			else return "enji, the Piercing Win (None)";
		case "048": if ($showPitch == false) return "Harmonized Kodachi";
			else return "Harmonized Kodachi (None)";
		case "049": if ($showPitch == false) return "Harmonized Kodachi";
			else return "Harmonized Kodachi (None)";
		case "050": if ($showPitch == false) return "Edge of Autumn";
			else return "Edge of Autumn (None)";
		case "051": if ($showPitch == false) return "Zephyr Needle";
			else return "Zephyr Needle (None)";
		case "052": if ($showPitch == false) return "Zephyr Needle";
			else return "Zephyr Needle (None)";
		case "053": if ($showPitch == false) return "Breeze Rider Boots";
			else return "Breeze Rider Boots (None)";
		case "054": if ($showPitch == false) return "Find Center";
			else return "Find Center (blue)";
		case "055": if ($showPitch == false) return "Flood of Force";
			else return "Flood of Force (yellow)";
		case "056": if ($showPitch == false) return "Heron's Flight";
			else return "Heron's Flight (red)";
		case "057": if ($showPitch == false) return "Crane Dance";
			else return "Crane Dance (red)";
		case "058": if ($showPitch == false) return "Crane Dance";
			else return "Crane Dance (yellow)";
		case "059": if ($showPitch == false) return "Crane Dance";
			else return "Crane Dance (blue)";
		case "060": if ($showPitch == false) return "Rushing River";
			else return "Rushing River (red)";
		case "061": if ($showPitch == false) return "Rushing River";
			else return "Rushing River (yellow)";
		case "062": if ($showPitch == false) return "Rushing River";
			else return "Rushing River (blue)";
		case "063": if ($showPitch == false) return "Flying Kick";
			else return "Flying Kick (red)";
		case "064": if ($showPitch == false) return "Flying Kick";
			else return "Flying Kick (yellow)";
		case "065": if ($showPitch == false) return "Flying Kick";
			else return "Flying Kick (blue)";
		case "066": if ($showPitch == false) return "Soulbead Strike";
			else return "Soulbead Strike (red)";
		case "067": if ($showPitch == false) return "Soulbead Strike";
			else return "Soulbead Strike (yellow)";
		case "068": if ($showPitch == false) return "Soulbead Strike";
			else return "Soulbead Strike (blue)";
		case "069": if ($showPitch == false) return "Torrent of Tempo";
			else return "Torrent of Tempo (red)";
		case "070": if ($showPitch == false) return "Torrent of Tempo";
			else return "Torrent of Tempo (yellow)";
		case "071": if ($showPitch == false) return "Torrent of Tempo";
			else return "Torrent of Tempo (blue)";
		case "072": if ($showPitch == false) return "Bittering Thorns";
			else return "Bittering Thorns (yellow)";
		case "073": if ($showPitch == false) return "Salt the Wound";
			else return "Salt the Wound (yellow)";
		case "074": if ($showPitch == false) return "Whirling Mist Blossom";
			else return "Whirling Mist Blossom (yellow)";
		case "075": if ($showPitch == false) return "Zen State";
			else return "Zen State (None)";
		case "076": if ($showPitch == false) return "Dorinthea Ironsong";
			else return "Dorinthea Ironsong (None)";
		case "077": if ($showPitch == false) return "assai, Cintari Sellswor";
			else return "assai, Cintari Sellswor (None)";
		case "078": if ($showPitch == false) return "Dawnblade";
			else return "Dawnblade (None)";
		case "079": if ($showPitch == false) return "Cintari Saber";
			else return "Cintari Saber (None)";
		case "080": if ($showPitch == false) return "Cintari Saber";
			else return "Cintari Saber (None)";
		case "081": if ($showPitch == false) return "Courage of Bladehold";
			else return "Courage of Bladehold (None)";
		case "082": if ($showPitch == false) return "Twinning Blade";
			else return "Twinning Blade (yellow)";
		case "083": if ($showPitch == false) return "Unified Decree";
			else return "Unified Decree (yellow)";
		case "084": if ($showPitch == false) return "Spoils of War";
			else return "Spoils of War (red)";
		case "085": if ($showPitch == false) return "Dauntless";
			else return "Dauntless (red)";
		case "086": if ($showPitch == false) return "Dauntless";
			else return "Dauntless (yellow)";
		case "087": if ($showPitch == false) return "Dauntless";
			else return "Dauntless (blue)";
		case "088": if ($showPitch == false) return "Out for Blood";
			else return "Out for Blood (red)";
		case "089": if ($showPitch == false) return "Out for Blood";
			else return "Out for Blood (yellow)";
		case "090": if ($showPitch == false) return "Out for Blood";
			else return "Out for Blood (blue)";
		case "091": if ($showPitch == false) return "Hit and Run";
			else return "Hit and Run (red)";
		case "092": if ($showPitch == false) return "Hit and Run";
			else return "Hit and Run (yellow)";
		case "093": if ($showPitch == false) return "Hit and Run";
			else return "Hit and Run (blue)";
		case "094": if ($showPitch == false) return "Push Forward";
			else return "Push Forward (red)";
		case "095": if ($showPitch == false) return "Push Forward";
			else return "Push Forward (yellow)";
		case "096": if ($showPitch == false) return "Push Forward";
			else return "Push Forward (blue)";
		case "097": if ($showPitch == false) return "riyana, Diamond Gemi";
			else return "riyana, Diamond Gemi (None)";
		case "098": if ($showPitch == false) return "Dash, Inventor Extraordinaire";
			else return "Dash, Inventor Extraordinaire (None)";
		case "099": if ($showPitch == false) return "Data Doll MKII";
			else return "Data Doll MKII (None)";
		case "100": if ($showPitch == false) return "Teklo Plasma Pistol";
			else return "Teklo Plasma Pistol (None)";
		case "101": if ($showPitch == false) return "Plasma Barrel Shot";
			else return "Plasma Barrel Shot (None)";
		case "102": if ($showPitch == false) return "Viziertronic Model i";
			else return "Viziertronic Model i (None)";
		case "103": if ($showPitch == false) return "Meganetic Shockwave";
			else return "Meganetic Shockwave (blue)";
		case "104": if ($showPitch == false) return "Absorption Dome";
			else return "Absorption Dome (yellow)";
		case "105": if ($showPitch == false) return "Plasma Purifier";
			else return "Plasma Purifier (red)";
		case "106": if ($showPitch == false) return "High Speed Impact";
			else return "High Speed Impact (red)";
		case "107": if ($showPitch == false) return "High Speed Impact";
			else return "High Speed Impact (yellow)";
		case "108": if ($showPitch == false) return "High Speed Impact";
			else return "High Speed Impact (blue)";
		case "109": if ($showPitch == false) return "Combustible Courier";
			else return "Combustible Courier (red)";
		case "110": if ($showPitch == false) return "Combustible Courier";
			else return "Combustible Courier (yellow)";
		case "111": if ($showPitch == false) return "Combustible Courier";
			else return "Combustible Courier (blue)";
		case "112": if ($showPitch == false) return "Overblast";
			else return "Overblast (red)";
		case "113": if ($showPitch == false) return "Overblast";
			else return "Overblast (yellow)";
		case "114": if ($showPitch == false) return "Overblast";
			else return "Overblast (blue)";
		case "115": if ($showPitch == false) return "Teklovossen's Workshop";
			else return "Teklovossen's Workshop (red)";
		case "116": if ($showPitch == false) return "Teklovossen's Workshop";
			else return "Teklovossen's Workshop (yellow)";
		case "117": if ($showPitch == false) return "Teklovossen's Workshop";
			else return "Teklovossen's Workshop (blue)";
		case "118": if ($showPitch == false) return ";Kavdaen, Trader of Skiy}s/";
			else return ";Kavdaen, Trader of Skiy}s/ (None)";
		case "119": if ($showPitch == false) return ":Azalea, Ace in the qug";
			else return ":Azalea, Ace in the qug (None)";
		case "120": if ($showPitch == false) return "Death Dealer";
			else return "Death Dealer (None)";
		case "121": if ($showPitch == false) return "Red Liner";
			else return "Red Liner (None)";
		case "122": if ($showPitch == false) return "Perch Grapplers";
			else return "Perch Grapplers (None)";
		case "123": if ($showPitch == false) return "Remorseless";
			else return "Remorseless (red)";
		case "124": if ($showPitch == false) return "Poison the Tips";
			else return "Poison the Tips (yellow)";
		case "125": if ($showPitch == false) return "Feign Death";
			else return "Feign Death (yellow)";
		case "126": if ($showPitch == false) return "Tripwire Trap";
			else return "Tripwire Trap (red)";
		case "127": if ($showPitch == false) return "Pitfall Trap";
			else return "Pitfall Trap (yellow)";
		case "128": if ($showPitch == false) return "Rockslide Trap";
			else return "Rockslide Trap (blue)";
		case "129": if ($showPitch == false) return "Pathing Helix";
			else return "Pathing Helix (red)";
		case "130": if ($showPitch == false) return "Pathing Helix";
			else return "Pathing Helix (yellow)";
		case "131": if ($showPitch == false) return "Pathing Helix";
			else return "Pathing Helix (blue)";
		case "132": if ($showPitch == false) return "Sleep Dart";
			else return "Sleep Dart (red)";
		case "133": if ($showPitch == false) return "Sleep Dart";
			else return "Sleep Dart (yellow)";
		case "134": if ($showPitch == false) return "Sleep Dart";
			else return "Sleep Dart (blue)";
		case "135": if ($showPitch == false) return "Increase the Tension";
			else return "Increase the Tension (red)";
		case "136": if ($showPitch == false) return "Increase the Tension";
			else return "Increase the Tension (yellow)";
		case "137": if ($showPitch == false) return "Increase the Tension";
			else return "Increase the Tension (blue)";
		case "138": if ($showPitch == false) return "Viserai, Rune Blood";
			else return "Viserai, Rune Blood (None)";
		case "139": if ($showPitch == false) return "Nebula Blade";
			else return "Nebula Blade (None)";
		case "140": if ($showPitch == false) return "Reaping Blade";
			else return "Reaping Blade (None)";
		case "141": if ($showPitch == false) return "Bloodsheath Skeleta";
			else return "Bloodsheath Skeleta (None)";
		case "142": if ($showPitch == false) return "Dread Triptych";
			else return "Dread Triptych (blue)";
		case "143": if ($showPitch == false) return "Rattle Bones";
			else return "Rattle Bones (red)";
		case "144": if ($showPitch == false) return "Runeblood Barrier";
			else return "Runeblood Barrier (yellow)";
		case "145": if ($showPitch == false) return "Mauvrion Skies";
			else return "Mauvrion Skies (red)";
		case "146": if ($showPitch == false) return "Mauvrion Skies";
			else return "Mauvrion Skies (yellow)";
		case "147": if ($showPitch == false) return "Mauvrion Skies";
			else return "Mauvrion Skies (blue)";
		case "148": if ($showPitch == false) return "Consuming Volition";
			else return "Consuming Volition (red)";
		case "149": if ($showPitch == false) return "Consuming Volition";
			else return "Consuming Volition (yellow)";
		case "150": if ($showPitch == false) return "Consuming Volition";
			else return "Consuming Volition (blue)";
		case "151": if ($showPitch == false) return "Meat and Greet";
			else return "Meat and Greet (red)";
		case "152": if ($showPitch == false) return "Meat and Greet";
			else return "Meat and Greet (yellow)";
		case "153": if ($showPitch == false) return "Meat and Greet";
			else return "Meat and Greet (blue)";
		case "154": if ($showPitch == false) return "Sutcliffe's Research Notes";
			else return "Sutcliffe's Research Notes (red)";
		case "155": if ($showPitch == false) return "Sutcliffe's Research Notes";
			else return "Sutcliffe's Research Notes (yellow)";
		case "156": if ($showPitch == false) return "Sutcliffe's Research Notes";
			else return "Sutcliffe's Research Notes (blue)";
		case "157": if ($showPitch == false) return "Runechant";
			else return "Runechant (None)";
		case "158": if ($showPitch == false) return "Cano, Dracai of Aether";
			else return "Cano, Dracai of Aether (None)";
		case "159": if ($showPitch == false) return "rucible of Aetherweay";
			else return "rucible of Aetherweay (None)";
		case "160": if ($showPitch == false) return "Aether Conduit";
			else return "Aether Conduit (None)";
		case "161": if ($showPitch == false) return "Metacarpus Node";
			else return "Metacarpus Node (None)";
		case "162": if ($showPitch == false) return "Chain Lightning";
			else return "Chain Lightning (yellow)";
		case "163": if ($showPitch == false) return "Gaze the Ages";
			else return "Gaze the Ages (blue)";
		case "164": if ($showPitch == false) return "Aetherize";
			else return "Aetherize (blue)";
		case "165": if ($showPitch == false) return "Cindering Foresight";
			else return "Cindering Foresight (red)";
		case "166": if ($showPitch == false) return "Cindering Foresight";
			else return "Cindering Foresight (yellow)";
		case "167": if ($showPitch == false) return "Cindering Foresight";
			else return "Cindering Foresight (blue)";
		case "168": if ($showPitch == false) return "Foreboding Bolt";
			else return "Foreboding Bolt (red)";
		case "169": if ($showPitch == false) return "Foreboding Bolt";
			else return "Foreboding Bolt (yellow)";
		case "170": if ($showPitch == false) return "Foreboding Bolt";
			else return "Foreboding Bolt (blue)";
		case "171": if ($showPitch == false) return "Rousing Aether";
			else return "Rousing Aether (red)";
		case "172": if ($showPitch == false) return "Rousing Aether";
			else return "Rousing Aether (yellow)";
		case "173": if ($showPitch == false) return "Rousing Aether";
			else return "Rousing Aether (blue)";
		case "174": if ($showPitch == false) return "Snapback";
			else return "Snapback (red)";
		case "175": if ($showPitch == false) return "Snapback";
			else return "Snapback (yellow)";
		case "176": if ($showPitch == false) return "Snapback";
			else return "Snapback (blue)";
		case "177": if ($showPitch == false) return "alishar, the Lost Princ";
			else return "alishar, the Lost Princ (None)";
		case "178": if ($showPitch == false) return "Fyendal's Spring Tunic";
			else return "Fyendal's Spring Tunic (None)";
		case "179": if ($showPitch == false) return "Gambler's Gloves";
			else return "Gambler's Gloves (None)";
		case "180": if ($showPitch == false) return "Coax a Commotion";
			else return "Coax a Commotion (red)";
		case "181": if ($showPitch == false) return "Gorganian Tome";
			else return "Gorganian Tome (None)";
		case "182": if ($showPitch == false) return "Shag";
			else return "Shag (blue)";
		case "183": if ($showPitch == false) return "Promise of Plenty";
			else return "Promise of Plenty (red)";
		case "184": if ($showPitch == false) return "Promise of Plenty";
			else return "Promise of Plenty (yellow)";
		case "185": if ($showPitch == false) return "Promise of Plenty";
			else return "Promise of Plenty (blue)";
		case "186": if ($showPitch == false) return "Lunging Press";
			else return "Lunging Press (blue)";
		case "187": if ($showPitch == false) return "Springboard Somersault";
			else return "Springboard Somersault (yellow)";
		case "188": if ($showPitch == false) return "Cash In";
			else return "Cash In (yellow)";
		case "189": if ($showPitch == false) return "Reinforce the Line";
			else return "Reinforce the Line (red)";
		case "190": if ($showPitch == false) return "Reinforce the Line";
			else return "Reinforce the Line (yellow)";
		case "191": if ($showPitch == false) return "Reinforce the Line";
			else return "Reinforce the Line (blue)";
		case "192": if ($showPitch == false) return "Brutal Assault";
			else return "Brutal Assault (red)";
		case "193": if ($showPitch == false) return "Brutal Assault";
			else return "Brutal Assault (yellow)";
		case "194": if ($showPitch == false) return "Brutal Assault";
			else return "Brutal Assault (blue)";
		case "195": if ($showPitch == false) return "Cracked Bauble";
			else return "Cracked Bauble (yellow)";
		case "196": if ($showPitch == false) return "Quicken";
			else return "Quicken (None)";
		case "197": if ($showPitch == false) return "Copper";
			else return "Copper (None)";

		   }	}
if ($set == "ELE")
	{  switch($num)	   {

		case "000": if ($showPitch == false) return "NWaper? -~ ©";
			else return "NWaper? -~ © (None)";
		case "001": if ($showPitch == false) return "him, Grandfather of Eter";
			else return "him, Grandfather of Eter (None)";
		case "002": if ($showPitch == false) return "Oldhim";
			else return "Oldhim (None)";
		case "003": if ($showPitch == false) return "Winter's Wail";
			else return "Winter's Wail (None)";
		case "004": if ($showPitch == false) return "Endless Winter";
			else return "Endless Winter (red)";
		case "005": if ($showPitch == false) return "Qaken Old";
			else return "Qaken Old (red)";
		case "006": if ($showPitch == false) return "Awakening";
			else return "Awakening (blue)";
		case "007": if ($showPitch == false) return "Biting Gale";
			else return "Biting Gale (red)";
		case "008": if ($showPitch == false) return "Biting Gale";
			else return "Biting Gale (yellow)";
		case "009": if ($showPitch == false) return "Biting Gale";
			else return "Biting Gale (blue)";
		case "010": if ($showPitch == false) return "Turn Timber";
			else return "Turn Timber (red)";
		case "011": if ($showPitch == false) return "Turn Timber";
			else return "Turn Timber (yellow)";
		case "012": if ($showPitch == false) return "Turn Timber";
			else return "Turn Timber (blue)";
		case "013": if ($showPitch == false) return "Entangle";
			else return "Entangle (red)";
		case "014": if ($showPitch == false) return "Entangle";
			else return "Entangle (yellow)";
		case "015": if ($showPitch == false) return "Entangle";
			else return "Entangle (blue)";
		case "016": if ($showPitch == false) return "Glacial Footsteps";
			else return "Glacial Footsteps (red)";
		case "017": if ($showPitch == false) return "Glacial Footsteps";
			else return "Glacial Footsteps (yellow)";
		case "018": if ($showPitch == false) return "Glacial Footsteps";
			else return "Glacial Footsteps (blue)";
		case "019": if ($showPitch == false) return "Mulch";
			else return "Mulch (red)";
		case "020": if ($showPitch == false) return "Mulch";
			else return "Mulch (yellow)";
		case "021": if ($showPitch == false) return "Mulch";
			else return "Mulch (blue)";
		case "022": if ($showPitch == false) return "Snow Under";
			else return "Snow Under (red)";
		case "023": if ($showPitch == false) return "Snow Under";
			else return "Snow Under (yellow)";
		case "024": if ($showPitch == false) return "Snow Under";
			else return "Snow Under (blue)";
		case "025": if ($showPitch == false) return "Emerging Avalanche";
			else return "Emerging Avalanche (red)";
		case "026": if ($showPitch == false) return "Emerging Avalanche";
			else return "Emerging Avalanche (yellow)";
		case "027": if ($showPitch == false) return "Emerging Avalanche";
			else return "Emerging Avalanche (blue)";
		case "028": if ($showPitch == false) return "Strength of Sequoia";
			else return "Strength of Sequoia (red)";
		case "029": if ($showPitch == false) return "Strength of Sequoia";
			else return "Strength of Sequoia (yellow)";
		case "030": if ($showPitch == false) return "Strength of Sequoia";
			else return "Strength of Sequoia (blue)";
		case "031": if ($showPitch == false) return "Lexi, Livewire";
			else return "Lexi, Livewire (None)";
		case "032": if ($showPitch == false) return "Lexi";
			else return "Lexi (None)";
		case "033": if ($showPitch == false) return "Shiver";
			else return "Shiver (None)";
		case "034": if ($showPitch == false) return "Voltaire, Strike Twice";
			else return "Voltaire, Strike Twice (None)";
		case "035": if ($showPitch == false) return "Frost Lock";
			else return "Frost Lock (blue)";
		case "036": if ($showPitch == false) return "Light it Up";
			else return "Light it Up (yellow)";
		case "037": if ($showPitch == false) return "lIce Storm";
			else return "lIce Storm (red)";
		case "038": if ($showPitch == false) return "Cold Wave";
			else return "Cold Wave (red)";
		case "039": if ($showPitch == false) return "Cold Wave";
			else return "Cold Wave (yellow)";
		case "040": if ($showPitch == false) return "Cold Wave";
			else return "Cold Wave (blue)";
		case "041": if ($showPitch == false) return "Snap Shot";
			else return "Snap Shot (red)";
		case "042": if ($showPitch == false) return "Snap Shot";
			else return "Snap Shot (yellow)";
		case "043": if ($showPitch == false) return "Snap Shot";
			else return "Snap Shot (blue)";
		case "044": if ($showPitch == false) return "Blizzard Bolt";
			else return "Blizzard Bolt (red)";
		case "045": if ($showPitch == false) return "Blizzard Bolt";
			else return "Blizzard Bolt (yellow)";
		case "046": if ($showPitch == false) return "Blizzard Bolt";
			else return "Blizzard Bolt (blue)";
		case "047": if ($showPitch == false) return "Buzz Bolt";
			else return "Buzz Bolt (red)";
		case "048": if ($showPitch == false) return "Buzz Bolt";
			else return "Buzz Bolt (yellow)";
		case "049": if ($showPitch == false) return "Buzz Bolt";
			else return "Buzz Bolt (blue)";
		case "050": if ($showPitch == false) return "Chilling Icevein";
			else return "Chilling Icevein (red)";
		case "051": if ($showPitch == false) return "Chilling Icevein";
			else return "Chilling Icevein (yellow)";
		case "052": if ($showPitch == false) return "Chilling Icevein";
			else return "Chilling Icevein (blue)";
		case "053": if ($showPitch == false) return "Dazzling Crescendo";
			else return "Dazzling Crescendo (red)";
		case "054": if ($showPitch == false) return "Dazzling Crescendo";
			else return "Dazzling Crescendo (yellow)";
		case "055": if ($showPitch == false) return "Dazzling Crescendo";
			else return "Dazzling Crescendo (blue)";
		case "056": if ($showPitch == false) return "Flake Out";
			else return "Flake Out (red)";
		case "057": if ($showPitch == false) return "Flake Out";
			else return "Flake Out (yellow)";
		case "058": if ($showPitch == false) return "Flake Out";
			else return "Flake Out (blue)";
		case "059": if ($showPitch == false) return "Frazzle";
			else return "Frazzle (red)";
		case "060": if ($showPitch == false) return "Frazzle";
			else return "Frazzle (yellow)";
		case "061": if ($showPitch == false) return "Frazzle";
			else return "Frazzle (blue)";
		case "062": if ($showPitch == false) return "riar, Warden of Thorn";
			else return "riar, Warden of Thorn (None)";
		case "063": if ($showPitch == false) return "Briar";
			else return "Briar (None)";
		case "064": if ($showPitch == false) return "Blossoming Spellblade";
			else return "Blossoming Spellblade (red)";
		case "065": if ($showPitch == false) return "Flicker Wisp";
			else return "Flicker Wisp (yellow)";
		case "066": if ($showPitch == false) return "Force of Nature";
			else return "Force of Nature (blue)";
		case "067": if ($showPitch == false) return "Explosive Growth";
			else return "Explosive Growth (red)";
		case "068": if ($showPitch == false) return "Explosive Growth";
			else return "Explosive Growth (yellow)";
		case "069": if ($showPitch == false) return "Explosive Growth";
			else return "Explosive Growth (blue)";
		case "070": if ($showPitch == false) return "Rites of Lightning";
			else return "Rites of Lightning (red)";
		case "071": if ($showPitch == false) return "Rites of Lightning";
			else return "Rites of Lightning (yellow)";
		case "072": if ($showPitch == false) return "Rites of Lightning";
			else return "Rites of Lightning (blue)";
		case "073": if ($showPitch == false) return "Arcanic Shockwave";
			else return "Arcanic Shockwave (red)";
		case "074": if ($showPitch == false) return "Arcanic Shockwave";
			else return "Arcanic Shockwave (yellow)";
		case "075": if ($showPitch == false) return "Arcanic Shockwave";
			else return "Arcanic Shockwave (blue)";
		case "076": if ($showPitch == false) return "Vela Flash";
			else return "Vela Flash (red)";
		case "077": if ($showPitch == false) return "Vela Flash";
			else return "Vela Flash (yellow)";
		case "078": if ($showPitch == false) return "Vela Flash";
			else return "Vela Flash (blue)";
		case "079": if ($showPitch == false) return "Rites of Replenishment";
			else return "Rites of Replenishment (red)";
		case "080": if ($showPitch == false) return "Rites of Replenishment";
			else return "Rites of Replenishment (yellow)";
		case "081": if ($showPitch == false) return "Rites of Replenishment";
			else return "Rites of Replenishment (blue)";
		case "082": if ($showPitch == false) return "Stir the Wildwood";
			else return "Stir the Wildwood (red)";
		case "083": if ($showPitch == false) return "Stir the Wildwood";
			else return "Stir the Wildwood (yellow)";
		case "084": if ($showPitch == false) return "Stir the Wildwood";
			else return "Stir the Wildwood (blue)";
		case "085": if ($showPitch == false) return "Bramble Spark";
			else return "Bramble Spark (red)";
		case "086": if ($showPitch == false) return "Bramble Spark";
			else return "Bramble Spark (yellow)";
		case "087": if ($showPitch == false) return "Bramble Spark";
			else return "Bramble Spark (blue)";
		case "088": if ($showPitch == false) return "Inspire Lightning";
			else return "Inspire Lightning (red)";
		case "089": if ($showPitch == false) return "Inspire Lightning";
			else return "Inspire Lightning (yellow)";
		case "090": if ($showPitch == false) return "Inspire Lightning";
			else return "Inspire Lightning (blue)";
		case "091": if ($showPitch == false) return "Fulminate";
			else return "Fulminate (yellow)";
		case "092": if ($showPitch == false) return "Flashfreeze";
			else return "Flashfreeze (red)";
		case "093": if ($showPitch == false) return "Exposed to the Elements";
			else return "Exposed to the Elements (blue)";
		case "094": if ($showPitch == false) return "Entwine Earth";
			else return "Entwine Earth (red)";
		case "095": if ($showPitch == false) return "Entwine Earth";
			else return "Entwine Earth (yellow)";
		case "096": if ($showPitch == false) return "Entwine Earth";
			else return "Entwine Earth (blue)";
		case "097": if ($showPitch == false) return "Entwine lce";
			else return "Entwine lce (red)";
		case "098": if ($showPitch == false) return "Entwine lce";
			else return "Entwine lce (yellow)";
		case "099": if ($showPitch == false) return "Entwine lce";
			else return "Entwine lce (blue)";
		case "100": if ($showPitch == false) return "Entwine Lightning";
			else return "Entwine Lightning (red)";
		case "101": if ($showPitch == false) return "Entwine Lightning";
			else return "Entwine Lightning (yellow)";
		case "102": if ($showPitch == false) return "Entwine Lightning";
			else return "Entwine Lightning (blue)";
		case "103": if ($showPitch == false) return "Invigorate";
			else return "Invigorate (red)";
		case "104": if ($showPitch == false) return "Invigorate";
			else return "Invigorate (yellow)";
		case "105": if ($showPitch == false) return "Invigorate";
			else return "Invigorate (blue)";
		case "106": if ($showPitch == false) return "Rejuvenate";
			else return "Rejuvenate (red)";
		case "107": if ($showPitch == false) return "Rejuvenate";
			else return "Rejuvenate (yellow)";
		case "108": if ($showPitch == false) return "Rejuvenate";
			else return "Rejuvenate (blue)";
		case "109": if ($showPitch == false) return "Embodiment of Earth";
			else return "Embodiment of Earth (None)";
		case "110": if ($showPitch == false) return "mbodiment of Lightnin";
			else return "mbodiment of Lightnin (None)";
		case "111": if ($showPitch == false) return "Frostbite";
			else return "Frostbite (None)";
		case "112": if ($showPitch == false) return "Pulse of Volthaven";
			else return "Pulse of Volthaven (red)";
		case "113": if ($showPitch == false) return "Pulse of Candlehold";
			else return "Pulse of Candlehold (yellow)";
		case "114": if ($showPitch == false) return "Pulse of Isenloft";
			else return "Pulse of Isenloft (blue)";
		case "115": if ($showPitch == false) return "Crown of Seeds";
			else return "Crown of Seeds (None)";
		case "116": if ($showPitch == false) return "Plume of Evergrowth";
			else return "Plume of Evergrowth (None)";
		case "117": if ($showPitch == false) return "Channel Mount Heroic";
			else return "Channel Mount Heroic (red)";
		case "118": if ($showPitch == false) return "Tome of Harvests";
			else return "Tome of Harvests (blue)";
		case "119": if ($showPitch == false) return "Evergreen";
			else return "Evergreen (red)";
		case "120": if ($showPitch == false) return "Evergreen";
			else return "Evergreen (yellow)";
		case "121": if ($showPitch == false) return "Evergreen";
			else return "Evergreen (blue)";
		case "122": if ($showPitch == false) return "Weave Earth";
			else return "Weave Earth (red)";
		case "123": if ($showPitch == false) return "Weave Earth";
			else return "Weave Earth (yellow)";
		case "124": if ($showPitch == false) return "Weave Earth";
			else return "Weave Earth (blue)";
		case "125": if ($showPitch == false) return "Summerwood Shelter";
			else return "Summerwood Shelter (red)";
		case "126": if ($showPitch == false) return "Summerwood Shelter";
			else return "Summerwood Shelter (yellow)";
		case "127": if ($showPitch == false) return "Summerwood Shelter";
			else return "Summerwood Shelter (blue)";
		case "128": if ($showPitch == false) return "Autumn's Touch";
			else return "Autumn's Touch (red)";
		case "129": if ($showPitch == false) return "Autumn's Touch";
			else return "Autumn's Touch (yellow)";
		case "130": if ($showPitch == false) return "Autumn's Touch";
			else return "Autumn's Touch (blue)";
		case "131": if ($showPitch == false) return "Break Ground";
			else return "Break Ground (red)";
		case "132": if ($showPitch == false) return "Break Ground";
			else return "Break Ground (yellow)";
		case "133": if ($showPitch == false) return "Break Ground";
			else return "Break Ground (blue)";
		case "134": if ($showPitch == false) return "Burgeoning";
			else return "Burgeoning (red)";
		case "135": if ($showPitch == false) return "Burgeoning";
			else return "Burgeoning (yellow)";
		case "136": if ($showPitch == false) return "Burgeoning";
			else return "Burgeoning (blue)";
		case "137": if ($showPitch == false) return "Earthlore Surge";
			else return "Earthlore Surge (red)";
		case "138": if ($showPitch == false) return "Earthlore Surge";
			else return "Earthlore Surge (yellow)";
		case "139": if ($showPitch == false) return "Earthlore Surge";
			else return "Earthlore Surge (blue)";
		case "140": if ($showPitch == false) return "Sow Tomorrow";
			else return "Sow Tomorrow (red)";
		case "141": if ($showPitch == false) return "Sow Tomorrow";
			else return "Sow Tomorrow (yellow)";
		case "142": if ($showPitch == false) return "Sow Tomorrow";
			else return "Sow Tomorrow (blue)";
		case "143": if ($showPitch == false) return "Amulet of Earth";
			else return "Amulet of Earth (blue)";
		case "144": if ($showPitch == false) return "Heart of Ice";
			else return "Heart of Ice (None)";
		case "145": if ($showPitch == false) return "Coat of Frost";
			else return "Coat of Frost (None)";
		case "146": if ($showPitch == false) return "Channel Lake Frigid";
			else return "Channel Lake Frigid (blue)";
		case "147": if ($showPitch == false) return "Blizzard";
			else return "Blizzard (blue)";
		case "148": if ($showPitch == false) return "Frost Fang";
			else return "Frost Fang (red)";
		case "149": if ($showPitch == false) return "Frost Fang";
			else return "Frost Fang (yellow)";
		case "150": if ($showPitch == false) return "Frost Fang";
			else return "Frost Fang (blue)";
		case "151": if ($showPitch == false) return "Ice Quake";
			else return "Ice Quake (red)";
		case "152": if ($showPitch == false) return "Ice Quake";
			else return "Ice Quake (yellow)";
		case "153": if ($showPitch == false) return "Ice Quake";
			else return "Ice Quake (blue)";
		case "154": if ($showPitch == false) return "Weave Ice";
			else return "Weave Ice (red)";
		case "155": if ($showPitch == false) return "Weave Ice";
			else return "Weave Ice (yellow)";
		case "156": if ($showPitch == false) return "Weave Ice";
			else return "Weave Ice (blue)";
		case "157": if ($showPitch == false) return "Icy Encounter";
			else return "Icy Encounter (red)";
		case "158": if ($showPitch == false) return "Icy Encounter";
			else return "Icy Encounter (yellow)";
		case "159": if ($showPitch == false) return "Icy Encounter";
			else return "Icy Encounter (blue)";
		case "160": if ($showPitch == false) return "Winter's Grasp";
			else return "Winter's Grasp (red)";
		case "161": if ($showPitch == false) return "Winter's Grasp";
			else return "Winter's Grasp (yellow)";
		case "162": if ($showPitch == false) return "Winter's Grasp";
			else return "Winter's Grasp (blue)";
		case "163": if ($showPitch == false) return "Chill to the Bone";
			else return "Chill to the Bone (red)";
		case "164": if ($showPitch == false) return "Chill to the Bone";
			else return "Chill to the Bone (yellow)";
		case "165": if ($showPitch == false) return "Chill to the Bone";
			else return "Chill to the Bone (blue)";
		case "166": if ($showPitch == false) return "Polar Blast";
			else return "Polar Blast (red)";
		case "167": if ($showPitch == false) return "Polar Blast";
			else return "Polar Blast (yellow)";
		case "168": if ($showPitch == false) return "Polar Blast";
			else return "Polar Blast (blue)";
		case "169": if ($showPitch == false) return "Winter's Bite";
			else return "Winter's Bite (red)";
		case "170": if ($showPitch == false) return "Winter's Bite";
			else return "Winter's Bite (yellow)";
		case "171": if ($showPitch == false) return "Winter's Bite";
			else return "Winter's Bite (blue)";
		case "172": if ($showPitch == false) return "Amulet of Ice";
			else return "Amulet of Ice (blue)";
		case "173": if ($showPitch == false) return "Shock Charmers";
			else return "Shock Charmers (None)";
		case "174": if ($showPitch == false) return "Mark of Lightning";
			else return "Mark of Lightning (None)";
		case "175": if ($showPitch == false) return "Channel Thunder Steppe";
			else return "Channel Thunder Steppe (yellow)";
		case "176": if ($showPitch == false) return "Blink";
			else return "Blink (blue)";
		case "177": if ($showPitch == false) return "Flash";
			else return "Flash (red)";
		case "178": if ($showPitch == false) return "Flash";
			else return "Flash (yellow)";
		case "179": if ($showPitch == false) return "Flash";
			else return "Flash (blue)";
		case "180": if ($showPitch == false) return "Weave Lightning";
			else return "Weave Lightning (red)";
		case "181": if ($showPitch == false) return "Weave Lightning";
			else return "Weave Lightning (yellow)";
		case "182": if ($showPitch == false) return "Weave Lightning";
			else return "Weave Lightning (blue)";
		case "183": if ($showPitch == false) return "Lightning Press";
			else return "Lightning Press (red)";
		case "184": if ($showPitch == false) return "Lightning Press";
			else return "Lightning Press (yellow)";
		case "185": if ($showPitch == false) return "Lightning Press";
			else return "Lightning Press (blue)";
		case "186": if ($showPitch == false) return "Ball Lightning";
			else return "Ball Lightning (red)";
		case "187": if ($showPitch == false) return "Ball Lightning";
			else return "Ball Lightning (yellow)";
		case "188": if ($showPitch == false) return "Ball Lightning";
			else return "Ball Lightning (blue)";
		case "189": if ($showPitch == false) return "Lightning Surge";
			else return "Lightning Surge (red)";
		case "190": if ($showPitch == false) return "Lightning Surge";
			else return "Lightning Surge (yellow)";
		case "191": if ($showPitch == false) return "Lightning Surge";
			else return "Lightning Surge (blue)";
		case "192": if ($showPitch == false) return "Heaven's Claws";
			else return "Heaven's Claws (red)";
		case "193": if ($showPitch == false) return "Heaven's Claws";
			else return "Heaven's Claws (yellow)";
		case "194": if ($showPitch == false) return "Heaven's Claws";
			else return "Heaven's Claws (blue)";
		case "195": if ($showPitch == false) return "Shock Striker";
			else return "Shock Striker (red)";
		case "196": if ($showPitch == false) return "Shock Striker";
			else return "Shock Striker (yellow)";
		case "197": if ($showPitch == false) return "Shock Striker";
			else return "Shock Striker (blue)";
		case "198": if ($showPitch == false) return "Electrify";
			else return "Electrify (red)";
		case "199": if ($showPitch == false) return "Electrify";
			else return "Electrify (yellow)";
		case "200": if ($showPitch == false) return "Electrify";
			else return "Electrify (blue)";
		case "201": if ($showPitch == false) return "Amulet of Lightning";
			else return "Amulet of Lightning (blue)";
		case "202": if ($showPitch == false) return "Titan's Fist";
			else return "Titan's Fist (None)";
		case "203": if ($showPitch == false) return "mpart of the Ram's He";
			else return "mpart of the Ram's He (None)";
		case "204": if ($showPitch == false) return "Rotten Old Buckler";
			else return "Rotten Old Buckler (None)";
		case "205": if ($showPitch == false) return "Tear Asunder";
			else return "Tear Asunder (blue)";
		case "206": if ($showPitch == false) return "Embolden";
			else return "Embolden (red)";
		case "207": if ($showPitch == false) return "Embolden";
			else return "Embolden (yellow)";
		case "208": if ($showPitch == false) return "Embolden";
			else return "Embolden (blue)";
		case "209": if ($showPitch == false) return "Thump";
			else return "Thump (red)";
		case "210": if ($showPitch == false) return "Thump";
			else return "Thump (yellow)";
		case "211": if ($showPitch == false) return "Thump";
			else return "Thump (blue)";
		case "212": if ($showPitch == false) return "Seismic Surge";
			else return "Seismic Surge (None)";
		case "213": if ($showPitch == false) return "New Horizon";
			else return "New Horizon (None)";
		case "214": if ($showPitch == false) return "Honing Hood";
			else return "Honing Hood (None)";
		case "215": if ($showPitch == false) return "Seek and Destroy";
			else return "Seek and Destroy (red)";
		case "216": if ($showPitch == false) return "Bolt'n' Shot";
			else return "Bolt'n' Shot (red)";
		case "217": if ($showPitch == false) return "Bolt'n' Shot";
			else return "Bolt'n' Shot (yellow)";
		case "218": if ($showPitch == false) return "Bolt'n' Shot";
			else return "Bolt'n' Shot (blue)";
		case "219": if ($showPitch == false) return "Over Flex";
			else return "Over Flex (red)";
		case "220": if ($showPitch == false) return "Over Flex";
			else return "Over Flex (yellow)";
		case "221": if ($showPitch == false) return "Over Flex";
			else return "Over Flex (blue)";
		case "222": if ($showPitch == false) return "Rosetta Thorn";
			else return "Rosetta Thorn (None)";
		case "223": if ($showPitch == false) return "Duskblade";
			else return "Duskblade (None)";
		case "224": if ($showPitch == false) return "Spellbound Creepers";
			else return "Spellbound Creepers (None)";
		case "225": if ($showPitch == false) return "Sutcliffe’'s Suede Hides";
			else return "Sutcliffe’'s Suede Hides (None)";
		case "226": if ($showPitch == false) return "Sting of Sorcery";
			else return "Sting of Sorcery (blue)";
		case "227": if ($showPitch == false) return "Sigil of Suffering";
			else return "Sigil of Suffering (red)";
		case "228": if ($showPitch == false) return "Sigil of Suffering";
			else return "Sigil of Suffering (yellow)";
		case "229": if ($showPitch == false) return "Sigil of Suffering";
			else return "Sigil of Suffering (blue)";
		case "230": if ($showPitch == false) return "Singeing Steelblade";
			else return "Singeing Steelblade (red)";
		case "231": if ($showPitch == false) return "Singeing Steelblade";
			else return "Singeing Steelblade (yellow)";
		case "232": if ($showPitch == false) return "Singeing Steelblade";
			else return "Singeing Steelblade (blue)";
		case "233": if ($showPitch == false) return "Ragamufhin's Hat";
			else return "Ragamufhin's Hat (None)";
		case "234": if ($showPitch == false) return "Deep Blue";
			else return "Deep Blue (None)";
		case "235": if ($showPitch == false) return "Cracker Jax";
			else return "Cracker Jax (None)";
		case "236": if ($showPitch == false) return "Runaways";
			else return "Runaways (None)";
		case "237": if ($showPitch == false) return "Cracked Bauble";
			else return "Cracked Bauble (yellow)";

		   }	}
if ($set == "MON")
	{  switch($num)	   {

		case "000": if ($showPitch == false) return "\N| W/";
			else return "\N| W/ (None)";
		case "001": if ($showPitch == false) return "sm, Sculptor of Arc Li";
			else return "sm, Sculptor of Arc Li (None)";
		case "002": if ($showPitch == false) return "Prism";
			else return "Prism (None)";
		case "003": if ($showPitch == false) return "Luminaris";
			else return "Luminaris (None)";
		case "004": if ($showPitch == false) return "Herald of Erudition";
			else return "Herald of Erudition (yellow)";
		case "005": if ($showPitch == false) return "Arc Light Sentinel";
			else return "Arc Light Sentinel (yellow)";
		case "006": if ($showPitch == false) return "Genesis";
			else return "Genesis (yellow)";
		case "007": if ($showPitch == false) return "Herald of Judgment";
			else return "Herald of Judgment (yellow)";
		case "008": if ($showPitch == false) return "Herald of Triumph";
			else return "Herald of Triumph (red)";
		case "009": if ($showPitch == false) return "Herald of Triumph";
			else return "Herald of Triumph (yellow)";
		case "010": if ($showPitch == false) return "Herald of Triumph";
			else return "Herald of Triumph (blue)";
		case "011": if ($showPitch == false) return "Parable of Humility";
			else return "Parable of Humility (yellow)";
		case "012": if ($showPitch == false) return "Merciful Retribution";
			else return "Merciful Retribution (yellow)";
		case "013": if ($showPitch == false) return "Qde to Wrath";
			else return "Qde to Wrath (yellow)";
		case "014": if ($showPitch == false) return "Herald of Protection";
			else return "Herald of Protection (red)";
		case "015": if ($showPitch == false) return "Herald of Protection";
			else return "Herald of Protection (yellow)";
		case "016": if ($showPitch == false) return "Herald of Protection";
			else return "Herald of Protection (blue)";
		case "017": if ($showPitch == false) return "Herald of Ravages";
			else return "Herald of Ravages (red)";
		case "018": if ($showPitch == false) return "Herald of Ravages";
			else return "Herald of Ravages (yellow)";
		case "019": if ($showPitch == false) return "Herald of Ravages";
			else return "Herald of Ravages (blue)";
		case "020": if ($showPitch == false) return "Herald of Rebirth";
			else return "Herald of Rebirth (red)";
		case "021": if ($showPitch == false) return "Herald of Rebirth";
			else return "Herald of Rebirth (yellow)";
		case "022": if ($showPitch == false) return "Herald of Rebirth";
			else return "Herald of Rebirth (blue)";
		case "023": if ($showPitch == false) return "Herald of Tenacity";
			else return "Herald of Tenacity (red)";
		case "024": if ($showPitch == false) return "Herald of Tenacity";
			else return "Herald of Tenacity (yellow)";
		case "025": if ($showPitch == false) return "Herald of Tenacity";
			else return "Herald of Tenacity (blue)";
		case "026": if ($showPitch == false) return "Wartune Herald";
			else return "Wartune Herald (red)";
		case "027": if ($showPitch == false) return "Wartune Herald";
			else return "Wartune Herald (yellow)";
		case "028": if ($showPitch == false) return "Wartune Herald";
			else return "Wartune Herald (blue)";
		case "029": if ($showPitch == false) return "Boltyn, Breaker of D:";
			else return "Boltyn, Breaker of D: (None)";
		case "030": if ($showPitch == false) return "Boltyn";
			else return "Boltyn (None)";
		case "031": if ($showPitch == false) return "Raydn, Duskbane";
			else return "Raydn, Duskbane (None)";
		case "032": if ($showPitch == false) return "Bolting Blade";
			else return "Bolting Blade (yellow)";
		case "033": if ($showPitch == false) return "Beacon of Victory";
			else return "Beacon of Victory (yellow)";
		case "034": if ($showPitch == false) return "Lumina Ascension";
			else return "Lumina Ascension (yellow)";
		case "035": if ($showPitch == false) return "V of the Vanguard";
			else return "V of the Vanguard (yellow)";
		case "036": if ($showPitch == false) return "Battlefield Blitz";
			else return "Battlefield Blitz (red)";
		case "037": if ($showPitch == false) return "Battlefield Blitz";
			else return "Battlefield Blitz (yellow)";
		case "038": if ($showPitch == false) return "Battlefield Blitz";
			else return "Battlefield Blitz (blue)";
		case "039": if ($showPitch == false) return "Valiant Thrust";
			else return "Valiant Thrust (red)";
		case "040": if ($showPitch == false) return "Valiant Thrust";
			else return "Valiant Thrust (yellow)";
		case "041": if ($showPitch == false) return "Valiant Thrust";
			else return "Valiant Thrust (blue)";
		case "042": if ($showPitch == false) return "Bolt of Courage";
			else return "Bolt of Courage (red)";
		case "043": if ($showPitch == false) return "Bolt of Courage";
			else return "Bolt of Courage (yellow)";

		   }	}

        return "";    }
             ?>
