<?php
function CardName ($cardID, $showPitch=true)
{
    $arr = str_split($cardID, 3);
    $set = $arr[0];
    $num = $arr[1];
    

if ($set == "ARC")
	{  switch($num)	   {

		case "000": if ($showPitch == false) return "Eye of Ophidia";
			else return "Eye of Ophidia (blue)";
		case "001": return "Dash, Inventor Extraordinaire";
		case "002": return "Dash";
		case "003": return "‘Teklo Plasma Pistol";
		case "004": return "Teklo Foundry Heart";
		case "005": return "Achilles Accelerator";
		case "006": if ($showPitch == false) return "High Octane";
			else return "High Octane (red)";
		case "007": if ($showPitch == false) return "Teklo Core";
			else return "Teklo Core (blue)";
		case "008": if ($showPitch == false) return "Maximum Velocity";
			else return "Maximum Velocity (red)";
		case "009": if ($showPitch == false) return "Spark of Genius";
			else return "Spark of Genius (yellow)";
		case "010": if ($showPitch == false) return "Induction Chamber";
			else return "Induction Chamber (red)";
		case "011": if ($showPitch == false) return "Pedal to the Metal";
			else return "Pedal to the Metal (red)";
		case "012": if ($showPitch == false) return "Pedal to the Metal";
			else return "Pedal to the Metal (yellow)";
		case "013": if ($showPitch == false) return "Pedal to the Metal";
			else return "Pedal to the Metal (blue)";
		case "014": if ($showPitch == false) return "Pour the Mold";
			else return "Pour the Mold (red)";
		case "015": if ($showPitch == false) return "Pour the Mold";
			else return "Pour the Mold (yellow)";
		case "016": if ($showPitch == false) return "Pour the Mold";
			else return "Pour the Mold (blue)";
		case "017": if ($showPitch == false) return "Aether Sink";
			else return "Aether Sink (yellow)";
		case "018": if ($showPitch == false) return "Cognition Nodes";
			else return "Cognition Nodes (blue)";
		case "019": if ($showPitch == false) return "Convection Amplifier";
			else return "Convection Amplifier (red)";
		case "020": if ($showPitch == false) return "Qver Loop";
			else return "Qver Loop (red)";
		case "021": if ($showPitch == false) return "Qver Loop";
			else return "Qver Loop (yellow)";
		case "022": if ($showPitch == false) return "Qver Loop";
			else return "Qver Loop (blue)";
		case "023": if ($showPitch == false) return "Throttle";
			else return "Throttle (red)";
		case "024": if ($showPitch == false) return "Throttle";
			else return "Throttle (yellow)";
		case "025": if ($showPitch == false) return "Throttle";
			else return "Throttle (blue)";
		case "026": if ($showPitch == false) return "Zero to Sixty";
			else return "Zero to Sixty (red)";
		case "027": if ($showPitch == false) return "Zero to Sixty";
			else return "Zero to Sixty (yellow)";
		case "028": if ($showPitch == false) return "Zero to Sixty";
			else return "Zero to Sixty (blue)";
		case "029": if ($showPitch == false) return "Zipper Hit";
			else return "Zipper Hit (red)";
		case "030": if ($showPitch == false) return "Zipper Hit";
			else return "Zipper Hit (yellow)";
		case "031": if ($showPitch == false) return "Zipper Hit";
			else return "Zipper Hit (blue)";
		case "032": if ($showPitch == false) return "Locked and Loaded";
			else return "Locked and Loaded (red)";
		case "033": if ($showPitch == false) return "Locked and Loaded";
			else return "Locked and Loaded (yellow)";
		case "034": if ($showPitch == false) return "Locked and Loaded";
			else return "Locked and Loaded (blue)";
		case "035": if ($showPitch == false) return "Dissipation Shield";
			else return "Dissipation Shield (yellow)";
		case "036": if ($showPitch == false) return "Hyper Driver";
			else return "Hyper Driver (red)";
		case "037": if ($showPitch == false) return "Optekal Monocle";
			else return "Optekal Monocle (blue)";
		case "038": return "Azalea, Ace in the Hole";
		case "039": return "£ Azalea o";
		case "040": return "Death Dealer";
		case "041": return "Skullbone Crosswrap";
		case "042": return "Bull's Eye Bracers";
		case "043": if ($showPitch == false) return "Red in the Ledger";
			else return "Red in the Ledger (red)";
		case "044": if ($showPitch == false) return "Three of a Kind";
			else return "Three of a Kind (red)";
		case "045": if ($showPitch == false) return "Endless Arrow";
			else return "Endless Arrow (red)";
		case "046": if ($showPitch == false) return "Nock the Deathwhistle";
			else return "Nock the Deathwhistle (blue)";
		case "047": if ($showPitch == false) return "Rapid Fire";
			else return "Rapid Fire (yellow)";
		case "048": if ($showPitch == false) return "Take Cover";
			else return "Take Cover (red)";
		case "049": if ($showPitch == false) return "Take Cover";
			else return "Take Cover (yellow)";
		case "050": if ($showPitch == false) return "Take Cover";
			else return "Take Cover (blue)";
		case "051": if ($showPitch == false) return "Silver the Tip";
			else return "Silver the Tip (red)";
		case "052": if ($showPitch == false) return "Silver the Tip";
			else return "Silver the Tip (yellow)";
		case "053": if ($showPitch == false) return "Silver the Tip";
			else return "Silver the Tip (blue)";
		case "054": if ($showPitch == false) return "Take Aim";
			else return "Take Aim (red)";
		case "055": if ($showPitch == false) return "Take Aim";
			else return "Take Aim (yellow)";
		case "056": if ($showPitch == false) return "Take Aim";
			else return "Take Aim (blue)";
		case "057": if ($showPitch == false) return "Head Shot";
			else return "Head Shot (red)";
		case "058": if ($showPitch == false) return "Head Shot";
			else return "Head Shot (yellow)";
		case "059": if ($showPitch == false) return "Head Shot";
			else return "Head Shot (blue)";
		case "060": if ($showPitch == false) return "Hamstring Shot";
			else return "Hamstring Shot (red)";
		case "061": if ($showPitch == false) return "Hamstring Shot";
			else return "Hamstring Shot (yellow)";
		case "062": if ($showPitch == false) return "Hamstring Shot";
			else return "Hamstring Shot (blue)";
		case "063": if ($showPitch == false) return "Ridge Rider Shot";
			else return "Ridge Rider Shot (red)";
		case "064": if ($showPitch == false) return "Ridge Rider Shot";
			else return "Ridge Rider Shot (yellow)";
		case "065": if ($showPitch == false) return "Ridge Rider Shot";
			else return "Ridge Rider Shot (blue)";
		case "066": if ($showPitch == false) return "Salvage Shot";
			else return "Salvage Shot (red)";
		case "067": if ($showPitch == false) return "Salvage Shot";
			else return "Salvage Shot (yellow)";
		case "068": if ($showPitch == false) return "Salvage Shot";
			else return "Salvage Shot (blue)";
		case "069": if ($showPitch == false) return "Searing Shot";
			else return "Searing Shot (red)";
		case "070": if ($showPitch == false) return "Searing Shot";
			else return "Searing Shot (yellow)";
		case "071": if ($showPitch == false) return "Searing Shot";
			else return "Searing Shot (blue)";
		case "072": if ($showPitch == false) return "Sic 'Em Shot";
			else return "Sic 'Em Shot (red)";
		case "073": if ($showPitch == false) return "Sic 'Em Shot";
			else return "Sic 'Em Shot (yellow)";
		case "074": if ($showPitch == false) return "Sic 'Em Shot";
			else return "Sic 'Em Shot (blue)";
		case "075": return "Viserai, Rune Blood";
		case "076": return "Viserai";
		case "077": return "Nebula Blade";
		case "078": return "Grasp of the Arknight";
		case "079": return "Crown of Dichotomy";
		case "080": if ($showPitch == false) return "Arknight Ascendancy";
			else return "Arknight Ascendancy (red)";
		case "081": if ($showPitch == false) return "Mordred Tide";
			else return "Mordred Tide (red)";
		case "082": if ($showPitch == false) return "Ninth Blade of the Blood Oatt";
			else return "Ninth Blade of the Blood Oatt (yellow)";
		case "083": if ($showPitch == false) return "Become the Arknight";
			else return "Become the Arknight (blue)";
		case "084": if ($showPitch == false) return "Tome of the Arknight";
			else return "Tome of the Arknight (blue)";
		case "085": if ($showPitch == false) return "Spellblade Assault";
			else return "Spellblade Assault (red)";
		case "086": if ($showPitch == false) return "Spellblade Assault";
			else return "Spellblade Assault (yellow)";
		case "087": if ($showPitch == false) return "Spellblade Assault";
			else return "Spellblade Assault (blue)";
		case "088": if ($showPitch == false) return "Reduce to Runechant";
			else return "Reduce to Runechant (red)";
		case "089": if ($showPitch == false) return "Reduce to Runechant";
			else return "Reduce to Runechant (yellow)";
		case "090": if ($showPitch == false) return "Reduce to Runechant";
			else return "Reduce to Runechant (blue)";
		case "091": if ($showPitch == false) return "Qath of the Arknight";
			else return "Qath of the Arknight (red)";
		case "092": if ($showPitch == false) return "Qath of the Arknight";
			else return "Qath of the Arknight (yellow)";
		case "093": if ($showPitch == false) return "Qath of the Arknight";
			else return "Qath of the Arknight (blue)";
		case "094": if ($showPitch == false) return "Amplify the Arknight";
			else return "Amplify the Arknight (red)";
		case "095": if ($showPitch == false) return "Amplify the Arknight";
			else return "Amplify the Arknight (yellow)";
		case "096": if ($showPitch == false) return "Amplify the Arknight";
			else return "Amplify the Arknight (blue)";
		case "097": if ($showPitch == false) return "Drawn to the Dark Dimension";
			else return "Drawn to the Dark Dimension (red)";
		case "098": if ($showPitch == false) return "Drawn to the Dark Dimension";
			else return "Drawn to the Dark Dimension (yellow)";
		case "099": if ($showPitch == false) return "Drawn to the Dark Dimension";
			else return "Drawn to the Dark Dimension (blue)";
		case "100": if ($showPitch == false) return "Rune Flash";
			else return "Rune Flash (red)";
		case "101": if ($showPitch == false) return "Rune Flash";
			else return "Rune Flash (yellow)";
		case "102": if ($showPitch == false) return "Rune Flash";
			else return "Rune Flash (blue)";
		case "103": if ($showPitch == false) return "Spellblade Strike";
			else return "Spellblade Strike (red)";
		case "104": if ($showPitch == false) return "Spellblade Strike";
			else return "Spellblade Strike (yellow)";
		case "105": if ($showPitch == false) return "Spellblade Strike";
			else return "Spellblade Strike (blue)";
		case "106": if ($showPitch == false) return "Bloodspill Invocation";
			else return "Bloodspill Invocation (red)";
		case "107": if ($showPitch == false) return "Bloodspill Invocation";
			else return "Bloodspill Invocation (yellow)";
		case "108": if ($showPitch == false) return "Bloodspill Invocation";
			else return "Bloodspill Invocation (blue)";
		case "109": if ($showPitch == false) return "Read the Runes";
			else return "Read the Runes (red)";
		case "110": if ($showPitch == false) return "Read the Runes";
			else return "Read the Runes (yellow)";
		case "111": if ($showPitch == false) return "Read the Runes";
			else return "Read the Runes (blue)";
		case "112": return "Runechant";
		case "113": return "Cano, Dracai of Aether";
		case "114": return "Kano";
		case "115": return "rucible of Aetherweav";
		case "116": return "Storm Striders";
		case "117": return "Robe of Rapture";
		case "118": if ($showPitch == false) return "~ Blazing Aether";
			else return "~ Blazing Aether (red)";
		case "119": if ($showPitch == false) return "Sonic Boom";
			else return "Sonic Boom (yellow)";
		case "120": if ($showPitch == false) return "Forked Lightning";
			else return "Forked Lightning (red)";
		case "121": if ($showPitch == false) return "Lesson in Lava";
			else return "Lesson in Lava (yellow)";
		case "122": if ($showPitch == false) return "Tome of Aetherwind";
			else return "Tome of Aetherwind (red)";
		case "123": if ($showPitch == false) return "Absorb in Aether";
			else return "Absorb in Aether (red)";
		case "124": if ($showPitch == false) return "Absorb in Aether";
			else return "Absorb in Aether (yellow)";
		case "125": if ($showPitch == false) return "Absorb in Aether";
			else return "Absorb in Aether (blue)";
		case "126": if ($showPitch == false) return "Aether Spindle";
			else return "Aether Spindle (red)";
		case "127": if ($showPitch == false) return "Aether Spindle";
			else return "Aether Spindle (yellow)";
		case "128": if ($showPitch == false) return "Aether Spindle";
			else return "Aether Spindle (blue)";
		case "129": if ($showPitch == false) return "Stir the Aetherwinds";
			else return "Stir the Aetherwinds (red)";
		case "130": if ($showPitch == false) return "Stir the Aetherwinds";
			else return "Stir the Aetherwinds (yellow)";
		case "131": if ($showPitch == false) return "Stir the Aetherwinds";
			else return "Stir the Aetherwinds (blue)";
		case "132": if ($showPitch == false) return "Aether Flare";
			else return "Aether Flare (red)";
		case "133": if ($showPitch == false) return "Aether Flare";
			else return "Aether Flare (yellow)";
		case "134": if ($showPitch == false) return "Aether Flare";
			else return "Aether Flare (blue)";
		case "135": if ($showPitch == false) return "Index";
			else return "Index (red)";
		case "136": if ($showPitch == false) return "Index";
			else return "Index (yellow)";
		case "137": if ($showPitch == false) return "Index";
			else return "Index (blue)";
		case "138": if ($showPitch == false) return "Reverberate";
			else return "Reverberate (red)";
		case "139": if ($showPitch == false) return "Reverberate";
			else return "Reverberate (yellow)";
		case "140": if ($showPitch == false) return "Reverberate";
			else return "Reverberate (blue)";
		case "141": if ($showPitch == false) return "Scalding Rain";
			else return "Scalding Rain (red)";
		case "142": if ($showPitch == false) return "Scalding Rain";
			else return "Scalding Rain (yellow)";
		case "143": if ($showPitch == false) return "Scalding Rain";
			else return "Scalding Rain (blue)";
		case "144": if ($showPitch == false) return "Zap";
			else return "Zap (red)";
		case "145": if ($showPitch == false) return "Zap";
			else return "Zap (yellow)";
		case "146": if ($showPitch == false) return "Zap";
			else return "Zap (blue)";
		case "147": if ($showPitch == false) return "Voltic Bolt";
			else return "Voltic Bolt (red)";
		case "148": if ($showPitch == false) return "Voltic Bolt";
			else return "Voltic Bolt (yellow)";
		case "149": if ($showPitch == false) return "Voltic Bolt";
			else return "Voltic Bolt (blue)";
		case "150": return "Arcanite Skullcap";
		case "151": return "Talismanic Lens";
		case "152": return "Vest of the First Fist";
		case "153": return "Bracers of Beliet";
		case "154": return "Mage Master Boots";
		case "155": return "Nullrune Hood";
		case "156": return "Nullrune Robe";
		case "157": return "Nullrune Gloves";
		case "158": return "Nullrune Boots";
		case "159": if ($showPitch == false) return "Command and Conquer";
			else return "Command and Conquer (red)";
		case "160": if ($showPitch == false) return "Art of War";
			else return "Art of War (yellow)";
		case "161": if ($showPitch == false) return "Pursuit of Knowledge";
			else return "Pursuit of Knowledge (blue)";
		case "162": if ($showPitch == false) return "Chains of Eminence";
			else return "Chains of Eminence (red)";
		case "163": if ($showPitch == false) return "Rusted Relic";
			else return "Rusted Relic (blue)";
		case "164": if ($showPitch == false) return "Life for a Life";
			else return "Life for a Life (red)";
		case "165": if ($showPitch == false) return "Life for a Life";
			else return "Life for a Life (yellow)";
		case "166": if ($showPitch == false) return "Life for a Life";
			else return "Life for a Life (blue)";
		case "167": if ($showPitch == false) return "Enchanting Melody";
			else return "Enchanting Melody (red)";
		case "168": if ($showPitch == false) return "Enchanting Melody";
			else return "Enchanting Melody (yellow)";
		case "169": if ($showPitch == false) return "Enchanting Melody";
			else return "Enchanting Melody (blue)";
		case "170": if ($showPitch == false) return "Plunder Run";
			else return "Plunder Run (red)";
		case "171": if ($showPitch == false) return "Plunder Run";
			else return "Plunder Run (yellow)";
		case "172": if ($showPitch == false) return "Plunder Run";
			else return "Plunder Run (blue)";
		case "173": if ($showPitch == false) return "Eirina's Prayer";
			else return "Eirina's Prayer (red)";
		case "174": if ($showPitch == false) return "Eirina's Prayer";
			else return "Eirina's Prayer (yellow)";
		case "175": if ($showPitch == false) return "Eirina's Prayer";
			else return "Eirina's Prayer (blue)";
		case "176": if ($showPitch == false) return "Back Alley Breakline";
			else return "Back Alley Breakline (red)";
		case "177": if ($showPitch == false) return "Back Alley Breakline";
			else return "Back Alley Breakline (yellow)";
		case "178": if ($showPitch == false) return "Back Alley Breakline";
			else return "Back Alley Breakline (blue)";
		case "179": if ($showPitch == false) return "Cadaverous Contraband";
			else return "Cadaverous Contraband (red)";
		case "180": if ($showPitch == false) return "Cadaverous Contraband";
			else return "Cadaverous Contraband (yellow)";
		case "181": if ($showPitch == false) return "Cadaverous Contraband";
			else return "Cadaverous Contraband (blue)";
		case "182": if ($showPitch == false) return "Fervent Forerunner";
			else return "Fervent Forerunner (red)";
		case "183": if ($showPitch == false) return "Fervent Forerunner";
			else return "Fervent Forerunner (yellow)";
		case "184": if ($showPitch == false) return "Fervent Forerunner";
			else return "Fervent Forerunner (blue)";
		case "185": if ($showPitch == false) return "Moon Wish";
			else return "Moon Wish (red)";
		case "186": if ($showPitch == false) return "Moon Wish";
			else return "Moon Wish (yellow)";
		case "187": if ($showPitch == false) return "Moon Wish";
			else return "Moon Wish (blue)";
		case "188": if ($showPitch == false) return "Push the Point";
			else return "Push the Point (red)";
		case "189": if ($showPitch == false) return "Push the Point";
			else return "Push the Point (yellow)";
		case "190": if ($showPitch == false) return "Push the Point";
			else return "Push the Point (blue)";
		case "191": if ($showPitch == false) return "Ravenous Rabble";
			else return "Ravenous Rabble (red)";
		case "192": if ($showPitch == false) return "Ravenous Rabble";
			else return "Ravenous Rabble (yellow)";
		case "193": if ($showPitch == false) return "Ravenous Rabble";
			else return "Ravenous Rabble (blue)";
		case "194": if ($showPitch == false) return "Rifting";
			else return "Rifting (red)";
		case "195": if ($showPitch == false) return "Rifting";
			else return "Rifting (yellow)";
		case "196": if ($showPitch == false) return "Rifting";
			else return "Rifting (blue)";
		case "197": if ($showPitch == false) return "Vigor Rush";
			else return "Vigor Rush (red)";
		case "198": if ($showPitch == false) return "Vigor Rush";
			else return "Vigor Rush (yellow)";
		case "199": if ($showPitch == false) return "Vigor Rush";
			else return "Vigor Rush (blue)";
		case "200": if ($showPitch == false) return "Fate Foreseen";
			else return "Fate Foreseen (red)";
		case "201": if ($showPitch == false) return "Fate Foreseen";
			else return "Fate Foreseen (yellow)";
		case "202": if ($showPitch == false) return "Fate Foreseen";
			else return "Fate Foreseen (blue)";
		case "203": if ($showPitch == false) return "Come to Fight";
			else return "Come to Fight (red)";
		case "204": if ($showPitch == false) return "Come to Fight";
			else return "Come to Fight (yellow)";
		case "205": if ($showPitch == false) return "Come to Fight";
			else return "Come to Fight (blue)";
		case "206": if ($showPitch == false) return "Force Sight";
			else return "Force Sight (red)";
		case "207": if ($showPitch == false) return "Force Sight";
			else return "Force Sight (yellow)";
		case "208": if ($showPitch == false) return "Force Sight";
			else return "Force Sight (blue)";
		case "209": if ($showPitch == false) return "Lead the Charge";
			else return "Lead the Charge (red)";
		case "210": if ($showPitch == false) return "Lead the Charge";
			else return "Lead the Charge (yellow)";
		case "211": if ($showPitch == false) return "Lead the Charge";
			else return "Lead the Charge (blue)";
		case "212": if ($showPitch == false) return "Sun Kiss";
			else return "Sun Kiss (red)";
		case "213": if ($showPitch == false) return "Sun Kiss";
			else return "Sun Kiss (yellow)";
		case "214": if ($showPitch == false) return "Sun Kiss";
			else return "Sun Kiss (blue)";
		case "215": if ($showPitch == false) return "Whisper of the Oracle";
			else return "Whisper of the Oracle (red)";
		case "216": if ($showPitch == false) return "Whisper of the Oracle";
			else return "Whisper of the Oracle (yellow)";
		case "217": if ($showPitch == false) return "Whisper of the Oracle";
			else return "Whisper of the Oracle (blue)";
		case "218": if ($showPitch == false) return "Cracked Bauble";
			else return "Cracked Bauble (yellow)";

		   }	}
if ($set == "CRU")
	{  switch($num)	   {

		case "000": if ($showPitch == false) return "Arknight Shard";
			else return "Arknight Shard (blue)";
		case "001": return "vinar, Reckless Rampa;";
		case "002": return "Kayo, Berserker Runt";
		case "003": return "Romping Club";
		case "004": return "Mandible Claw";
		case "005": return "Mandible Claw";
		case "006": return "Skullhorn";
		case "007": if ($showPitch == false) return "Beast Within";
			else return "Beast Within (yellow)";
		case "008": if ($showPitch == false) return "Massacre";
			else return "Massacre (red)";
		case "009": if ($showPitch == false) return "Argh... Smash!";
			else return "Argh... Smash! (yellow)";
		case "010": if ($showPitch == false) return "Barraging Big Horn";
			else return "Barraging Big Horn (red)";
		case "011": if ($showPitch == false) return "Barraging Big Horn";
			else return "Barraging Big Horn (yellow)";
		case "012": if ($showPitch == false) return "Barraging Big Horn";
			else return "Barraging Big Horn (blue)";
		case "013": if ($showPitch == false) return "Predatory Assault";
			else return "Predatory Assault (red)";
		case "014": if ($showPitch == false) return "Predatory Assault";
			else return "Predatory Assault (yellow)";
		case "015": if ($showPitch == false) return "Predatory Assault";
			else return "Predatory Assault (blue)";
		case "016": if ($showPitch == false) return "Riled Up";
			else return "Riled Up (red)";
		case "017": if ($showPitch == false) return "Riled Up";
			else return "Riled Up (yellow)";
		case "018": if ($showPitch == false) return "Riled Up";
			else return "Riled Up (blue)";
		case "019": if ($showPitch == false) return "Swing Fist, Think Later";
			else return "Swing Fist, Think Later (red)";
		case "020": if ($showPitch == false) return "Swing Fist, Think Later";
			else return "Swing Fist, Think Later (yellow)";
		case "021": if ($showPitch == false) return "Swing Fist, Think Later";
			else return "Swing Fist, Think Later (blue)";
		case "022": return "Bravo, Showstopper";
		case "023": return "Anothos";
		case "024": return "Sledge of Anvilheim";
		case "025": return "Crater Fist";
		case "026": if ($showPitch == false) return "Mangle";
			else return "Mangle (red)";
		case "027": if ($showPitch == false) return "Righteous Cleansing";
			else return "Righteous Cleansing (yellow)";
		case "028": if ($showPitch == false) return "Stamp Authority";
			else return "Stamp Authority (blue)";
		case "029": if ($showPitch == false) return "Towering Titan";
			else return "Towering Titan (red)";
		case "030": if ($showPitch == false) return "Towering Titan";
			else return "Towering Titan (yellow)";
		case "031": if ($showPitch == false) return "Towering Titan";
			else return "Towering Titan (blue)";
		case "032": if ($showPitch == false) return "Crush the Weak";
			else return "Crush the Weak (red)";
		case "033": if ($showPitch == false) return "Crush the Weak";
			else return "Crush the Weak (yellow)";
		case "034": if ($showPitch == false) return "Crush the Weak";
			else return "Crush the Weak (blue)";
		case "035": if ($showPitch == false) return "Chokeslam";
			else return "Chokeslam (red)";
		case "036": if ($showPitch == false) return "Chokeslam";
			else return "Chokeslam (yellow)";
		case "037": if ($showPitch == false) return "Chokeslam";
			else return "Chokeslam (blue)";
		case "038": if ($showPitch == false) return "Emerging Dominance";
			else return "Emerging Dominance (red)";
		case "039": if ($showPitch == false) return "Emerging Dominance";
			else return "Emerging Dominance (yellow)";
		case "040": if ($showPitch == false) return "Emerging Dominance";
			else return "Emerging Dominance (blue)";
		case "041": if ($showPitch == false) return "Blessing of Serenity";
			else return "Blessing of Serenity (red)";
		case "042": if ($showPitch == false) return "Blessing of Serenity";
			else return "Blessing of Serenity (yellow)";
		case "043": if ($showPitch == false) return "Blessing of Serenity";
			else return "Blessing of Serenity (blue)";
		case "044": return "Seismic Surge";
		case "045": return "Katsu, the Wanderer";
		case "046": return "Ira, Crimson Haze";
		case "047": return "enji, the Piercing Win";
		case "048": return "Harmonized Kodachi";
		case "049": return "Harmonized Kodachi";
		case "050": return "Edge of Autumn";
		case "051": return "Zephyr Needle";
		case "052": return "Zephyr Needle";
		case "053": return "Breeze Rider Boots";
		case "054": if ($showPitch == false) return "Find Center";
			else return "Find Center (blue)";
		case "055": if ($showPitch == false) return "Flood of Force";
			else return "Flood of Force (yellow)";
		case "056": if ($showPitch == false) return "Heron's Flight";
			else return "Heron's Flight (red)";
		case "057": if ($showPitch == false) return "Crane Dance";
			else return "Crane Dance (red)";
		case "058": if ($showPitch == false) return "Crane Dance";
			else return "Crane Dance (yellow)";
		case "059": if ($showPitch == false) return "Crane Dance";
			else return "Crane Dance (blue)";
		case "060": if ($showPitch == false) return "Rushing River";
			else return "Rushing River (red)";
		case "061": if ($showPitch == false) return "Rushing River";
			else return "Rushing River (yellow)";
		case "062": if ($showPitch == false) return "Rushing River";
			else return "Rushing River (blue)";
		case "063": if ($showPitch == false) return "Flying Kick";
			else return "Flying Kick (red)";
		case "064": if ($showPitch == false) return "Flying Kick";
			else return "Flying Kick (yellow)";
		case "065": if ($showPitch == false) return "Flying Kick";
			else return "Flying Kick (blue)";
		case "066": if ($showPitch == false) return "Soulbead Strike";
			else return "Soulbead Strike (red)";
		case "067": if ($showPitch == false) return "Soulbead Strike";
			else return "Soulbead Strike (yellow)";
		case "068": if ($showPitch == false) return "Soulbead Strike";
			else return "Soulbead Strike (blue)";
		case "069": if ($showPitch == false) return "Torrent of Tempo";
			else return "Torrent of Tempo (red)";
		case "070": if ($showPitch == false) return "Torrent of Tempo";
			else return "Torrent of Tempo (yellow)";
		case "071": if ($showPitch == false) return "Torrent of Tempo";
			else return "Torrent of Tempo (blue)";
		case "072": if ($showPitch == false) return "Bittering Thorns";
			else return "Bittering Thorns (yellow)";
		case "073": if ($showPitch == false) return "Salt the Wound";
			else return "Salt the Wound (yellow)";
		case "074": if ($showPitch == false) return "Whirling Mist Blossom";
			else return "Whirling Mist Blossom (yellow)";
		case "075": return "Zen State";
		case "076": return "Dorinthea Ironsong";
		case "077": return "assai, Cintari Sellswor";
		case "078": return "Dawnblade";
		case "079": return "Cintari Saber";
		case "080": return "Cintari Saber";
		case "081": return "Courage of Bladehold";
		case "082": if ($showPitch == false) return "Twinning Blade";
			else return "Twinning Blade (yellow)";
		case "083": if ($showPitch == false) return "Unified Decree";
			else return "Unified Decree (yellow)";
		case "084": if ($showPitch == false) return "Spoils of War";
			else return "Spoils of War (red)";
		case "085": if ($showPitch == false) return "Dauntless";
			else return "Dauntless (red)";
		case "086": if ($showPitch == false) return "Dauntless";
			else return "Dauntless (yellow)";
		case "087": if ($showPitch == false) return "Dauntless";
			else return "Dauntless (blue)";
		case "088": if ($showPitch == false) return "Out for Blood";
			else return "Out for Blood (red)";
		case "089": if ($showPitch == false) return "Out for Blood";
			else return "Out for Blood (yellow)";
		case "090": if ($showPitch == false) return "Out for Blood";
			else return "Out for Blood (blue)";
		case "091": if ($showPitch == false) return "Hit and Run";
			else return "Hit and Run (red)";
		case "092": if ($showPitch == false) return "Hit and Run";
			else return "Hit and Run (yellow)";
		case "093": if ($showPitch == false) return "Hit and Run";
			else return "Hit and Run (blue)";
		case "094": if ($showPitch == false) return "Push Forward";
			else return "Push Forward (red)";
		case "095": if ($showPitch == false) return "Push Forward";
			else return "Push Forward (yellow)";
		case "096": if ($showPitch == false) return "Push Forward";
			else return "Push Forward (blue)";
		case "097": return "riyana, Diamond Gemi";
		case "098": return "Dash, Inventor Extraordinaire";
		case "099": return "Data Doll MKII";
		case "100": return "Teklo Plasma Pistol";
		case "101": return "Plasma Barrel Shot";
		case "102": return "Viziertronic Model i";
		case "103": if ($showPitch == false) return "Meganetic Shockwave";
			else return "Meganetic Shockwave (blue)";
		case "104": if ($showPitch == false) return "Absorption Dome";
			else return "Absorption Dome (yellow)";
		case "105": if ($showPitch == false) return "Plasma Purifier";
			else return "Plasma Purifier (red)";
		case "106": if ($showPitch == false) return "High Speed Impact";
			else return "High Speed Impact (red)";
		case "107": if ($showPitch == false) return "High Speed Impact";
			else return "High Speed Impact (yellow)";
		case "108": if ($showPitch == false) return "High Speed Impact";
			else return "High Speed Impact (blue)";
		case "109": if ($showPitch == false) return "Combustible Courier";
			else return "Combustible Courier (red)";
		case "110": if ($showPitch == false) return "Combustible Courier";
			else return "Combustible Courier (yellow)";
		case "111": if ($showPitch == false) return "Combustible Courier";
			else return "Combustible Courier (blue)";
		case "112": if ($showPitch == false) return "Overblast";
			else return "Overblast (red)";
		case "113": if ($showPitch == false) return "Overblast";
			else return "Overblast (yellow)";
		case "114": if ($showPitch == false) return "Overblast";
			else return "Overblast (blue)";
		case "115": if ($showPitch == false) return "Teklovossen's Workshop";
			else return "Teklovossen's Workshop (red)";
		case "116": if ($showPitch == false) return "Teklovossen's Workshop";
			else return "Teklovossen's Workshop (yellow)";
		case "117": if ($showPitch == false) return "Teklovossen's Workshop";
			else return "Teklovossen's Workshop (blue)";
		case "118": return ";Kavdaen, Trader of Skiy}s/";
		case "119": return ":Azalea, Ace in the qug";
		case "120": return "Death Dealer";
		case "121": return "Red Liner";
		case "122": return "Perch Grapplers";
		case "123": if ($showPitch == false) return "Remorseless";
			else return "Remorseless (red)";
		case "124": if ($showPitch == false) return "Poison the Tips";
			else return "Poison the Tips (yellow)";
		case "125": if ($showPitch == false) return "Feign Death";
			else return "Feign Death (yellow)";
		case "126": if ($showPitch == false) return "Tripwire Trap";
			else return "Tripwire Trap (red)";
		case "127": if ($showPitch == false) return "Pitfall Trap";
			else return "Pitfall Trap (yellow)";
		case "128": if ($showPitch == false) return "Rockslide Trap";
			else return "Rockslide Trap (blue)";
		case "129": if ($showPitch == false) return "Pathing Helix";
			else return "Pathing Helix (red)";
		case "130": if ($showPitch == false) return "Pathing Helix";
			else return "Pathing Helix (yellow)";
		case "131": if ($showPitch == false) return "Pathing Helix";
			else return "Pathing Helix (blue)";
		case "132": if ($showPitch == false) return "Sleep Dart";
			else return "Sleep Dart (red)";
		case "133": if ($showPitch == false) return "Sleep Dart";
			else return "Sleep Dart (yellow)";
		case "134": if ($showPitch == false) return "Sleep Dart";
			else return "Sleep Dart (blue)";
		case "135": if ($showPitch == false) return "Increase the Tension";
			else return "Increase the Tension (red)";
		case "136": if ($showPitch == false) return "Increase the Tension";
			else return "Increase the Tension (yellow)";
		case "137": if ($showPitch == false) return "Increase the Tension";
			else return "Increase the Tension (blue)";
		case "138": return "Viserai, Rune Blood";
		case "139": return "Nebula Blade";
		case "140": return "Reaping Blade";
		case "141": return "Bloodsheath Skeleta";
		case "142": if ($showPitch == false) return "Dread Triptych";
			else return "Dread Triptych (blue)";
		case "143": if ($showPitch == false) return "Rattle Bones";
			else return "Rattle Bones (red)";
		case "144": if ($showPitch == false) return "Runeblood Barrier";
			else return "Runeblood Barrier (yellow)";
		case "145": if ($showPitch == false) return "Mauvrion Skies";
			else return "Mauvrion Skies (red)";
		case "146": if ($showPitch == false) return "Mauvrion Skies";
			else return "Mauvrion Skies (yellow)";
		case "147": if ($showPitch == false) return "Mauvrion Skies";
			else return "Mauvrion Skies (blue)";
		case "148": if ($showPitch == false) return "Consuming Volition";
			else return "Consuming Volition (red)";
		case "149": if ($showPitch == false) return "Consuming Volition";
			else return "Consuming Volition (yellow)";
		case "150": if ($showPitch == false) return "Consuming Volition";
			else return "Consuming Volition (blue)";
		case "151": if ($showPitch == false) return "Meat and Greet";
			else return "Meat and Greet (red)";
		case "152": if ($showPitch == false) return "Meat and Greet";
			else return "Meat and Greet (yellow)";
		case "153": if ($showPitch == false) return "Meat and Greet";
			else return "Meat and Greet (blue)";
		case "154": if ($showPitch == false) return "Sutcliffe's Research Notes";
			else return "Sutcliffe's Research Notes (red)";
		case "155": if ($showPitch == false) return "Sutcliffe's Research Notes";
			else return "Sutcliffe's Research Notes (yellow)";
		case "156": if ($showPitch == false) return "Sutcliffe's Research Notes";
			else return "Sutcliffe's Research Notes (blue)";
		case "157": return "Runechant";
		case "158": return "Cano, Dracai of Aether";
		case "159": return "rucible of Aetherweay";
		case "160": return "Aether Conduit";
		case "161": return "Metacarpus Node";
		case "162": if ($showPitch == false) return "Chain Lightning";
			else return "Chain Lightning (yellow)";
		case "163": if ($showPitch == false) return "Gaze the Ages";
			else return "Gaze the Ages (blue)";
		case "164": if ($showPitch == false) return "Aetherize";
			else return "Aetherize (blue)";
		case "165": if ($showPitch == false) return "Cindering Foresight";
			else return "Cindering Foresight (red)";
		case "166": if ($showPitch == false) return "Cindering Foresight";
			else return "Cindering Foresight (yellow)";
		case "167": if ($showPitch == false) return "Cindering Foresight";
			else return "Cindering Foresight (blue)";
		case "168": if ($showPitch == false) return "Foreboding Bolt";
			else return "Foreboding Bolt (red)";
		case "169": if ($showPitch == false) return "Foreboding Bolt";
			else return "Foreboding Bolt (yellow)";
		case "170": if ($showPitch == false) return "Foreboding Bolt";
			else return "Foreboding Bolt (blue)";
		case "171": if ($showPitch == false) return "Rousing Aether";
			else return "Rousing Aether (red)";
		case "172": if ($showPitch == false) return "Rousing Aether";
			else return "Rousing Aether (yellow)";
		case "173": if ($showPitch == false) return "Rousing Aether";
			else return "Rousing Aether (blue)";
		case "174": if ($showPitch == false) return "Snapback";
			else return "Snapback (red)";
		case "175": if ($showPitch == false) return "Snapback";
			else return "Snapback (yellow)";
		case "176": if ($showPitch == false) return "Snapback";
			else return "Snapback (blue)";
		case "177": return "alishar, the Lost Princ";
		case "178": return "Fyendal's Spring Tunic";
		case "179": return "Gambler's Gloves";
		case "180": if ($showPitch == false) return "Coax a Commotion";
			else return "Coax a Commotion (red)";
		case "181": return "Gorganian Tome";
		case "182": if ($showPitch == false) return "Shag";
			else return "Shag (blue)";
		case "183": if ($showPitch == false) return "Promise of Plenty";
			else return "Promise of Plenty (red)";
		case "184": if ($showPitch == false) return "Promise of Plenty";
			else return "Promise of Plenty (yellow)";
		case "185": if ($showPitch == false) return "Promise of Plenty";
			else return "Promise of Plenty (blue)";
		case "186": if ($showPitch == false) return "Lunging Press";
			else return "Lunging Press (blue)";
		case "187": if ($showPitch == false) return "Springboard Somersault";
			else return "Springboard Somersault (yellow)";
		case "188": if ($showPitch == false) return "Cash In";
			else return "Cash In (yellow)";
		case "189": if ($showPitch == false) return "Reinforce the Line";
			else return "Reinforce the Line (red)";
		case "190": if ($showPitch == false) return "Reinforce the Line";
			else return "Reinforce the Line (yellow)";
		case "191": if ($showPitch == false) return "Reinforce the Line";
			else return "Reinforce the Line (blue)";
		case "192": if ($showPitch == false) return "Brutal Assault";
			else return "Brutal Assault (red)";
		case "193": if ($showPitch == false) return "Brutal Assault";
			else return "Brutal Assault (yellow)";
		case "194": if ($showPitch == false) return "Brutal Assault";
			else return "Brutal Assault (blue)";
		case "195": if ($showPitch == false) return "Cracked Bauble";
			else return "Cracked Bauble (yellow)";
		case "196": return "Quicken";
		case "197": return "Copper";

		   }	}
if ($set == "ELE")
	{  switch($num)	   {

		case "000": return "Korshem, Crossroad of Element";
		case "001": return "him, Grandfather of Eter";
		case "002": return "Oldhim";
		case "003": return "Winter's Wail";
		case "004": if ($showPitch == false) return "Endless Winter";
			else return "Endless Winter (red)";
		case "005": if ($showPitch == false) return "Qaken Old";
			else return "Qaken Old (red)";
		case "006": if ($showPitch == false) return "Awakening";
			else return "Awakening (blue)";
		case "007": if ($showPitch == false) return "Biting Gale";
			else return "Biting Gale (red)";
		case "008": if ($showPitch == false) return "Biting Gale";
			else return "Biting Gale (yellow)";
		case "009": if ($showPitch == false) return "Biting Gale";
			else return "Biting Gale (blue)";
		case "010": if ($showPitch == false) return "Turn Timber";
			else return "Turn Timber (red)";
		case "011": if ($showPitch == false) return "Turn Timber";
			else return "Turn Timber (yellow)";
		case "012": if ($showPitch == false) return "Turn Timber";
			else return "Turn Timber (blue)";
		case "013": if ($showPitch == false) return "Entangle";
			else return "Entangle (red)";
		case "014": if ($showPitch == false) return "Entangle";
			else return "Entangle (yellow)";
		case "015": if ($showPitch == false) return "Entangle";
			else return "Entangle (blue)";
		case "016": if ($showPitch == false) return "Glacial Footsteps";
			else return "Glacial Footsteps (red)";
		case "017": if ($showPitch == false) return "Glacial Footsteps";
			else return "Glacial Footsteps (yellow)";
		case "018": if ($showPitch == false) return "Glacial Footsteps";
			else return "Glacial Footsteps (blue)";
		case "019": if ($showPitch == false) return "Mulch";
			else return "Mulch (red)";
		case "020": if ($showPitch == false) return "Mulch";
			else return "Mulch (yellow)";
		case "021": if ($showPitch == false) return "Mulch";
			else return "Mulch (blue)";
		case "022": if ($showPitch == false) return "Snow Under";
			else return "Snow Under (red)";
		case "023": if ($showPitch == false) return "Snow Under";
			else return "Snow Under (yellow)";
		case "024": if ($showPitch == false) return "Snow Under";
			else return "Snow Under (blue)";
		case "025": if ($showPitch == false) return "Emerging Avalanche";
			else return "Emerging Avalanche (red)";
		case "026": if ($showPitch == false) return "Emerging Avalanche";
			else return "Emerging Avalanche (yellow)";
		case "027": if ($showPitch == false) return "Emerging Avalanche";
			else return "Emerging Avalanche (blue)";
		case "028": if ($showPitch == false) return "Strength of Sequoia";
			else return "Strength of Sequoia (red)";
		case "029": if ($showPitch == false) return "Strength of Sequoia";
			else return "Strength of Sequoia (yellow)";
		case "030": if ($showPitch == false) return "Strength of Sequoia";
			else return "Strength of Sequoia (blue)";
		case "031": return "Lexi, Livewire";
		case "032": return "Lexi";
		case "033": return "Shiver";
		case "034": return "Voltaire, Strike Twice";
		case "035": if ($showPitch == false) return "Frost Lock";
			else return "Frost Lock (blue)";
		case "036": if ($showPitch == false) return "Light it Up";
			else return "Light it Up (yellow)";
		case "037": if ($showPitch == false) return "lIce Storm";
			else return "lIce Storm (red)";
		case "038": if ($showPitch == false) return "Cold Wave";
			else return "Cold Wave (red)";
		case "039": if ($showPitch == false) return "Cold Wave";
			else return "Cold Wave (yellow)";
		case "040": if ($showPitch == false) return "Cold Wave";
			else return "Cold Wave (blue)";
		case "041": if ($showPitch == false) return "Snap Shot";
			else return "Snap Shot (red)";
		case "042": if ($showPitch == false) return "Snap Shot";
			else return "Snap Shot (yellow)";
		case "043": if ($showPitch == false) return "Snap Shot";
			else return "Snap Shot (blue)";
		case "044": if ($showPitch == false) return "Blizzard Bolt";
			else return "Blizzard Bolt (red)";
		case "045": if ($showPitch == false) return "Blizzard Bolt";
			else return "Blizzard Bolt (yellow)";
		case "046": if ($showPitch == false) return "Blizzard Bolt";
			else return "Blizzard Bolt (blue)";
		case "047": if ($showPitch == false) return "Buzz Bolt";
			else return "Buzz Bolt (red)";
		case "048": if ($showPitch == false) return "Buzz Bolt";
			else return "Buzz Bolt (yellow)";
		case "049": if ($showPitch == false) return "Buzz Bolt";
			else return "Buzz Bolt (blue)";
		case "050": if ($showPitch == false) return "Chilling Icevein";
			else return "Chilling Icevein (red)";
		case "051": if ($showPitch == false) return "Chilling Icevein";
			else return "Chilling Icevein (yellow)";
		case "052": if ($showPitch == false) return "Chilling Icevein";
			else return "Chilling Icevein (blue)";
		case "053": if ($showPitch == false) return "Dazzling Crescendo";
			else return "Dazzling Crescendo (red)";
		case "054": if ($showPitch == false) return "Dazzling Crescendo";
			else return "Dazzling Crescendo (yellow)";
		case "055": if ($showPitch == false) return "Dazzling Crescendo";
			else return "Dazzling Crescendo (blue)";
		case "056": if ($showPitch == false) return "Flake Out";
			else return "Flake Out (red)";
		case "057": if ($showPitch == false) return "Flake Out";
			else return "Flake Out (yellow)";
		case "058": if ($showPitch == false) return "Flake Out";
			else return "Flake Out (blue)";
		case "059": if ($showPitch == false) return "Frazzle";
			else return "Frazzle (red)";
		case "060": if ($showPitch == false) return "Frazzle";
			else return "Frazzle (yellow)";
		case "061": if ($showPitch == false) return "Frazzle";
			else return "Frazzle (blue)";
		case "062": return "riar, Warden of Thorn";
		case "063": return "Briar";
		case "064": if ($showPitch == false) return "Blossoming Spellblade";
			else return "Blossoming Spellblade (red)";
		case "065": if ($showPitch == false) return "Flicker Wisp";
			else return "Flicker Wisp (yellow)";
		case "066": if ($showPitch == false) return "Force of Nature";
			else return "Force of Nature (blue)";
		case "067": if ($showPitch == false) return "Explosive Growth";
			else return "Explosive Growth (red)";
		case "068": if ($showPitch == false) return "Explosive Growth";
			else return "Explosive Growth (yellow)";
		case "069": if ($showPitch == false) return "Explosive Growth";
			else return "Explosive Growth (blue)";
		case "070": if ($showPitch == false) return "Rites of Lightning";
			else return "Rites of Lightning (red)";
		case "071": if ($showPitch == false) return "Rites of Lightning";
			else return "Rites of Lightning (yellow)";
		case "072": if ($showPitch == false) return "Rites of Lightning";
			else return "Rites of Lightning (blue)";
		case "073": if ($showPitch == false) return "Arcanic Shockwave";
			else return "Arcanic Shockwave (red)";
		case "074": if ($showPitch == false) return "Arcanic Shockwave";
			else return "Arcanic Shockwave (yellow)";
		case "075": if ($showPitch == false) return "Arcanic Shockwave";
			else return "Arcanic Shockwave (blue)";
		case "076": if ($showPitch == false) return "Vela Flash";
			else return "Vela Flash (red)";
		case "077": if ($showPitch == false) return "Vela Flash";
			else return "Vela Flash (yellow)";
		case "078": if ($showPitch == false) return "Vela Flash";
			else return "Vela Flash (blue)";
		case "079": if ($showPitch == false) return "Rites of Replenishment";
			else return "Rites of Replenishment (red)";
		case "080": if ($showPitch == false) return "Rites of Replenishment";
			else return "Rites of Replenishment (yellow)";
		case "081": if ($showPitch == false) return "Rites of Replenishment";
			else return "Rites of Replenishment (blue)";
		case "082": if ($showPitch == false) return "Stir the Wildwood";
			else return "Stir the Wildwood (red)";
		case "083": if ($showPitch == false) return "Stir the Wildwood";
			else return "Stir the Wildwood (yellow)";
		case "084": if ($showPitch == false) return "Stir the Wildwood";
			else return "Stir the Wildwood (blue)";
		case "085": if ($showPitch == false) return "Bramble Spark";
			else return "Bramble Spark (red)";
		case "086": if ($showPitch == false) return "Bramble Spark";
			else return "Bramble Spark (yellow)";
		case "087": if ($showPitch == false) return "Bramble Spark";
			else return "Bramble Spark (blue)";
		case "088": if ($showPitch == false) return "Inspire Lightning";
			else return "Inspire Lightning (red)";
		case "089": if ($showPitch == false) return "Inspire Lightning";
			else return "Inspire Lightning (yellow)";
		case "090": if ($showPitch == false) return "Inspire Lightning";
			else return "Inspire Lightning (blue)";
		case "091": if ($showPitch == false) return "Fulminate";
			else return "Fulminate (yellow)";
		case "092": if ($showPitch == false) return "Flashfreeze";
			else return "Flashfreeze (red)";
		case "093": if ($showPitch == false) return "Exposed to the Elements";
			else return "Exposed to the Elements (blue)";
		case "094": if ($showPitch == false) return "Entwine Earth";
			else return "Entwine Earth (red)";
		case "095": if ($showPitch == false) return "Entwine Earth";
			else return "Entwine Earth (yellow)";
		case "096": if ($showPitch == false) return "Entwine Earth";
			else return "Entwine Earth (blue)";
		case "097": if ($showPitch == false) return "Entwine lce";
			else return "Entwine lce (red)";
		case "098": if ($showPitch == false) return "Entwine lce";
			else return "Entwine lce (yellow)";
		case "099": if ($showPitch == false) return "Entwine lce";
			else return "Entwine lce (blue)";
		case "100": if ($showPitch == false) return "Entwine Lightning";
			else return "Entwine Lightning (red)";
		case "101": if ($showPitch == false) return "Entwine Lightning";
			else return "Entwine Lightning (yellow)";
		case "102": if ($showPitch == false) return "Entwine Lightning";
			else return "Entwine Lightning (blue)";
		case "103": if ($showPitch == false) return "Invigorate";
			else return "Invigorate (red)";
		case "104": if ($showPitch == false) return "Invigorate";
			else return "Invigorate (yellow)";
		case "105": if ($showPitch == false) return "Invigorate";
			else return "Invigorate (blue)";
		case "106": if ($showPitch == false) return "Rejuvenate";
			else return "Rejuvenate (red)";
		case "107": if ($showPitch == false) return "Rejuvenate";
			else return "Rejuvenate (yellow)";
		case "108": if ($showPitch == false) return "Rejuvenate";
			else return "Rejuvenate (blue)";
		case "109": return "Embodiment of Earth";
		case "110": return "mbodiment of Lightnin";
		case "111": return "Frostbite";
		case "112": if ($showPitch == false) return "Pulse of Volthaven";
			else return "Pulse of Volthaven (red)";
		case "113": if ($showPitch == false) return "Pulse of Candlehold";
			else return "Pulse of Candlehold (yellow)";
		case "114": if ($showPitch == false) return "Pulse of Isenloft";
			else return "Pulse of Isenloft (blue)";
		case "115": return "Crown of Seeds";
		case "116": return "Plume of Evergrowth";
		case "117": if ($showPitch == false) return "Channel Mount Heroic";
			else return "Channel Mount Heroic (red)";
		case "118": if ($showPitch == false) return "Tome of Harvests";
			else return "Tome of Harvests (blue)";
		case "119": if ($showPitch == false) return "Evergreen";
			else return "Evergreen (red)";
		case "120": if ($showPitch == false) return "Evergreen";
			else return "Evergreen (yellow)";
		case "121": if ($showPitch == false) return "Evergreen";
			else return "Evergreen (blue)";
		case "122": if ($showPitch == false) return "Weave Earth";
			else return "Weave Earth (red)";
		case "123": if ($showPitch == false) return "Weave Earth";
			else return "Weave Earth (yellow)";
		case "124": if ($showPitch == false) return "Weave Earth";
			else return "Weave Earth (blue)";
		case "125": if ($showPitch == false) return "Summerwood Shelter";
			else return "Summerwood Shelter (red)";
		case "126": if ($showPitch == false) return "Summerwood Shelter";
			else return "Summerwood Shelter (yellow)";
		case "127": if ($showPitch == false) return "Summerwood Shelter";
			else return "Summerwood Shelter (blue)";
		case "128": if ($showPitch == false) return "Autumn's Touch";
			else return "Autumn's Touch (red)";
		case "129": if ($showPitch == false) return "Autumn's Touch";
			else return "Autumn's Touch (yellow)";
		case "130": if ($showPitch == false) return "Autumn's Touch";
			else return "Autumn's Touch (blue)";
		case "131": if ($showPitch == false) return "Break Ground";
			else return "Break Ground (red)";
		case "132": if ($showPitch == false) return "Break Ground";
			else return "Break Ground (yellow)";
		case "133": if ($showPitch == false) return "Break Ground";
			else return "Break Ground (blue)";
		case "134": if ($showPitch == false) return "Burgeoning";
			else return "Burgeoning (red)";
		case "135": if ($showPitch == false) return "Burgeoning";
			else return "Burgeoning (yellow)";
		case "136": if ($showPitch == false) return "Burgeoning";
			else return "Burgeoning (blue)";
		case "137": if ($showPitch == false) return "Earthlore Surge";
			else return "Earthlore Surge (red)";
		case "138": if ($showPitch == false) return "Earthlore Surge";
			else return "Earthlore Surge (yellow)";
		case "139": if ($showPitch == false) return "Earthlore Surge";
			else return "Earthlore Surge (blue)";
		case "140": if ($showPitch == false) return "Sow Tomorrow";
			else return "Sow Tomorrow (red)";
		case "141": if ($showPitch == false) return "Sow Tomorrow";
			else return "Sow Tomorrow (yellow)";
		case "142": if ($showPitch == false) return "Sow Tomorrow";
			else return "Sow Tomorrow (blue)";
		case "143": if ($showPitch == false) return "Amulet of Earth";
			else return "Amulet of Earth (blue)";
		case "144": return "Heart of Ice";
		case "145": return "Coat of Frost";
		case "146": if ($showPitch == false) return "Channel Lake Frigid";
			else return "Channel Lake Frigid (blue)";
		case "147": if ($showPitch == false) return "Blizzard";
			else return "Blizzard (blue)";
		case "148": if ($showPitch == false) return "Frost Fang";
			else return "Frost Fang (red)";
		case "149": if ($showPitch == false) return "Frost Fang";
			else return "Frost Fang (yellow)";
		case "150": if ($showPitch == false) return "Frost Fang";
			else return "Frost Fang (blue)";
		case "151": if ($showPitch == false) return "Ice Quake";
			else return "Ice Quake (red)";
		case "152": if ($showPitch == false) return "Ice Quake";
			else return "Ice Quake (yellow)";
		case "153": if ($showPitch == false) return "Ice Quake";
			else return "Ice Quake (blue)";
		case "154": if ($showPitch == false) return "Weave Ice";
			else return "Weave Ice (red)";
		case "155": if ($showPitch == false) return "Weave Ice";
			else return "Weave Ice (yellow)";
		case "156": if ($showPitch == false) return "Weave Ice";
			else return "Weave Ice (blue)";
		case "157": if ($showPitch == false) return "Icy Encounter";
			else return "Icy Encounter (red)";
		case "158": if ($showPitch == false) return "Icy Encounter";
			else return "Icy Encounter (yellow)";
		case "159": if ($showPitch == false) return "Icy Encounter";
			else return "Icy Encounter (blue)";
		case "160": if ($showPitch == false) return "Winter's Grasp";
			else return "Winter's Grasp (red)";
		case "161": if ($showPitch == false) return "Winter's Grasp";
			else return "Winter's Grasp (yellow)";
		case "162": if ($showPitch == false) return "Winter's Grasp";
			else return "Winter's Grasp (blue)";
		case "163": if ($showPitch == false) return "Chill to the Bone";
			else return "Chill to the Bone (red)";
		case "164": if ($showPitch == false) return "Chill to the Bone";
			else return "Chill to the Bone (yellow)";
		case "165": if ($showPitch == false) return "Chill to the Bone";
			else return "Chill to the Bone (blue)";
		case "166": if ($showPitch == false) return "Polar Blast";
			else return "Polar Blast (red)";
		case "167": if ($showPitch == false) return "Polar Blast";
			else return "Polar Blast (yellow)";
		case "168": if ($showPitch == false) return "Polar Blast";
			else return "Polar Blast (blue)";
		case "169": if ($showPitch == false) return "Winter's Bite";
			else return "Winter's Bite (red)";
		case "170": if ($showPitch == false) return "Winter's Bite";
			else return "Winter's Bite (yellow)";
		case "171": if ($showPitch == false) return "Winter's Bite";
			else return "Winter's Bite (blue)";
		case "172": if ($showPitch == false) return "Amulet of Ice";
			else return "Amulet of Ice (blue)";
		case "173": return "Shock Charmers";
		case "174": return "Mark of Lightning";
		case "175": if ($showPitch == false) return "Channel Thunder Steppe";
			else return "Channel Thunder Steppe (yellow)";
		case "176": if ($showPitch == false) return "Blink";
			else return "Blink (blue)";
		case "177": if ($showPitch == false) return "Flash";
			else return "Flash (red)";
		case "178": if ($showPitch == false) return "Flash";
			else return "Flash (yellow)";
		case "179": if ($showPitch == false) return "Flash";
			else return "Flash (blue)";
		case "180": if ($showPitch == false) return "Weave Lightning";
			else return "Weave Lightning (red)";
		case "181": if ($showPitch == false) return "Weave Lightning";
			else return "Weave Lightning (yellow)";
		case "182": if ($showPitch == false) return "Weave Lightning";
			else return "Weave Lightning (blue)";
		case "183": if ($showPitch == false) return "Lightning Press";
			else return "Lightning Press (red)";
		case "184": if ($showPitch == false) return "Lightning Press";
			else return "Lightning Press (yellow)";
		case "185": if ($showPitch == false) return "Lightning Press";
			else return "Lightning Press (blue)";
		case "186": if ($showPitch == false) return "Ball Lightning";
			else return "Ball Lightning (red)";
		case "187": if ($showPitch == false) return "Ball Lightning";
			else return "Ball Lightning (yellow)";
		case "188": if ($showPitch == false) return "Ball Lightning";
			else return "Ball Lightning (blue)";
		case "189": if ($showPitch == false) return "Lightning Surge";
			else return "Lightning Surge (red)";
		case "190": if ($showPitch == false) return "Lightning Surge";
			else return "Lightning Surge (yellow)";
		case "191": if ($showPitch == false) return "Lightning Surge";
			else return "Lightning Surge (blue)";
		case "192": if ($showPitch == false) return "Heaven's Claws";
			else return "Heaven's Claws (red)";
		case "193": if ($showPitch == false) return "Heaven's Claws";
			else return "Heaven's Claws (yellow)";
		case "194": if ($showPitch == false) return "Heaven's Claws";
			else return "Heaven's Claws (blue)";
		case "195": if ($showPitch == false) return "Shock Striker";
			else return "Shock Striker (red)";
		case "196": if ($showPitch == false) return "Shock Striker";
			else return "Shock Striker (yellow)";
		case "197": if ($showPitch == false) return "Shock Striker";
			else return "Shock Striker (blue)";
		case "198": if ($showPitch == false) return "Electrify";
			else return "Electrify (red)";
		case "199": if ($showPitch == false) return "Electrify";
			else return "Electrify (yellow)";
		case "200": if ($showPitch == false) return "Electrify";
			else return "Electrify (blue)";
		case "201": if ($showPitch == false) return "Amulet of Lightning";
			else return "Amulet of Lightning (blue)";
		case "202": return "Titan's Fist";
		case "203": return "mpart of the Ram's He";
		case "204": return "Rotten Old Buckler";
		case "205": if ($showPitch == false) return "Tear Asunder";
			else return "Tear Asunder (blue)";
		case "206": if ($showPitch == false) return "Embolden";
			else return "Embolden (red)";
		case "207": if ($showPitch == false) return "Embolden";
			else return "Embolden (yellow)";
		case "208": if ($showPitch == false) return "Embolden";
			else return "Embolden (blue)";
		case "209": if ($showPitch == false) return "Thump";
			else return "Thump (red)";
		case "210": if ($showPitch == false) return "Thump";
			else return "Thump (yellow)";
		case "211": if ($showPitch == false) return "Thump";
			else return "Thump (blue)";
		case "212": return "Seismic Surge";
		case "213": return "New Horizon";
		case "214": return "Honing Hood";
		case "215": if ($showPitch == false) return "Seek and Destroy";
			else return "Seek and Destroy (red)";
		case "216": if ($showPitch == false) return "Bolt'n' Shot";
			else return "Bolt'n' Shot (red)";
		case "217": if ($showPitch == false) return "Bolt'n' Shot";
			else return "Bolt'n' Shot (yellow)";
		case "218": if ($showPitch == false) return "Bolt'n' Shot";
			else return "Bolt'n' Shot (blue)";
		case "219": if ($showPitch == false) return "Over Flex";
			else return "Over Flex (red)";
		case "220": if ($showPitch == false) return "Over Flex";
			else return "Over Flex (yellow)";
		case "221": if ($showPitch == false) return "Over Flex";
			else return "Over Flex (blue)";
		case "222": return "Rosetta Thorn";
		case "223": return "Duskblade";
		case "224": return "Spellbound Creepers";
		case "225": return "Sutcliffe’'s Suede Hides";
		case "226": if ($showPitch == false) return "Sting of Sorcery";
			else return "Sting of Sorcery (blue)";
		case "227": if ($showPitch == false) return "Sigil of Suffering";
			else return "Sigil of Suffering (red)";
		case "228": if ($showPitch == false) return "Sigil of Suffering";
			else return "Sigil of Suffering (yellow)";
		case "229": if ($showPitch == false) return "Sigil of Suffering";
			else return "Sigil of Suffering (blue)";
		case "230": if ($showPitch == false) return "Singeing Steelblade";
			else return "Singeing Steelblade (red)";
		case "231": if ($showPitch == false) return "Singeing Steelblade";
			else return "Singeing Steelblade (yellow)";
		case "232": if ($showPitch == false) return "Singeing Steelblade";
			else return "Singeing Steelblade (blue)";
		case "233": return "Ragamufhin's Hat";
		case "234": return "Deep Blue";
		case "235": return "Cracker Jax";
		case "236": return "Runaways";
		case "237": if ($showPitch == false) return "Cracked Bauble";
			else return "Cracked Bauble (yellow)";

		   }	}
if ($set == "MON")
	{  switch($num)	   {

		case "000": return "The Great Library of Solan";
		case "001": return "sm, Sculptor of Arc Li";
		case "002": return "Prism";
		case "003": return "Luminaris";
		case "004": if ($showPitch == false) return "Herald of Erudition";
			else return "Herald of Erudition (yellow)";
		case "005": if ($showPitch == false) return "Arc Light Sentinel";
			else return "Arc Light Sentinel (yellow)";
		case "006": if ($showPitch == false) return "Genesis";
			else return "Genesis (yellow)";
		case "007": if ($showPitch == false) return "Herald of Judgment";
			else return "Herald of Judgment (yellow)";
		case "008": if ($showPitch == false) return "Herald of Triumph";
			else return "Herald of Triumph (red)";
		case "009": if ($showPitch == false) return "Herald of Triumph";
			else return "Herald of Triumph (yellow)";
		case "010": if ($showPitch == false) return "Herald of Triumph";
			else return "Herald of Triumph (blue)";
		case "011": if ($showPitch == false) return "Parable of Humility";
			else return "Parable of Humility (yellow)";
		case "012": if ($showPitch == false) return "Merciful Retribution";
			else return "Merciful Retribution (yellow)";
		case "013": if ($showPitch == false) return "Qde to Wrath";
			else return "Qde to Wrath (yellow)";
		case "014": if ($showPitch == false) return "Herald of Protection";
			else return "Herald of Protection (red)";
		case "015": if ($showPitch == false) return "Herald of Protection";
			else return "Herald of Protection (yellow)";
		case "016": if ($showPitch == false) return "Herald of Protection";
			else return "Herald of Protection (blue)";
		case "017": if ($showPitch == false) return "Herald of Ravages";
			else return "Herald of Ravages (red)";
		case "018": if ($showPitch == false) return "Herald of Ravages";
			else return "Herald of Ravages (yellow)";
		case "019": if ($showPitch == false) return "Herald of Ravages";
			else return "Herald of Ravages (blue)";
		case "020": if ($showPitch == false) return "Herald of Rebirth";
			else return "Herald of Rebirth (red)";
		case "021": if ($showPitch == false) return "Herald of Rebirth";
			else return "Herald of Rebirth (yellow)";
		case "022": if ($showPitch == false) return "Herald of Rebirth";
			else return "Herald of Rebirth (blue)";
		case "023": if ($showPitch == false) return "Herald of Tenacity";
			else return "Herald of Tenacity (red)";
		case "024": if ($showPitch == false) return "Herald of Tenacity";
			else return "Herald of Tenacity (yellow)";
		case "025": if ($showPitch == false) return "Herald of Tenacity";
			else return "Herald of Tenacity (blue)";
		case "026": if ($showPitch == false) return "Wartune Herald";
			else return "Wartune Herald (red)";
		case "027": if ($showPitch == false) return "Wartune Herald";
			else return "Wartune Herald (yellow)";
		case "028": if ($showPitch == false) return "Wartune Herald";
			else return "Wartune Herald (blue)";
		case "029": return "Boltyn, Breaker of D:";
		case "030": return "Boltyn";
		case "031": return "Raydn, Duskbane";
		case "032": if ($showPitch == false) return "Bolting Blade";
			else return "Bolting Blade (yellow)";
		case "033": if ($showPitch == false) return "Beacon of Victory";
			else return "Beacon of Victory (yellow)";
		case "034": if ($showPitch == false) return "Lumina Ascension";
			else return "Lumina Ascension (yellow)";
		case "035": if ($showPitch == false) return "V of the Vanguard";
			else return "V of the Vanguard (yellow)";
		case "036": if ($showPitch == false) return "Battlefield Blitz";
			else return "Battlefield Blitz (red)";
		case "037": if ($showPitch == false) return "Battlefield Blitz";
			else return "Battlefield Blitz (yellow)";
		case "038": if ($showPitch == false) return "Battlefield Blitz";
			else return "Battlefield Blitz (blue)";
		case "039": if ($showPitch == false) return "Valiant Thrust";
			else return "Valiant Thrust (red)";
		case "040": if ($showPitch == false) return "Valiant Thrust";
			else return "Valiant Thrust (yellow)";
		case "041": if ($showPitch == false) return "Valiant Thrust";
			else return "Valiant Thrust (blue)";
		case "042": if ($showPitch == false) return "Bolt of Courage";
			else return "Bolt of Courage (red)";
		case "043": if ($showPitch == false) return "Bolt of Courage";
			else return "Bolt of Courage (yellow)";
		case "044": if ($showPitch == false) return "Bolt of Courage";
			else return "Bolt of Courage (blue)";
		case "045": if ($showPitch == false) return "Cross the Line";
			else return "Cross the Line (red)";
		case "046": if ($showPitch == false) return "Cross the Line";
			else return "Cross the Line (yellow)";
		case "047": if ($showPitch == false) return "Cross the Line";
			else return "Cross the Line (blue)";
		case "048": if ($showPitch == false) return "Engulfing Light";
			else return "Engulfing Light (red)";
		case "049": if ($showPitch == false) return "Engulfing Light";
			else return "Engulfing Light (yellow)";
		case "050": if ($showPitch == false) return "Engulfing Light";
			else return "Engulfing Light (blue)";
		case "051": if ($showPitch == false) return "Express Lightning";
			else return "Express Lightning (red)";
		case "052": if ($showPitch == false) return "Express Lightning";
			else return "Express Lightning (yellow)";
		case "053": if ($showPitch == false) return "Express Lightning";
			else return "Express Lightning (blue)";
		case "054": if ($showPitch == false) return "Take Flight";
			else return "Take Flight (red)";
		case "055": if ($showPitch == false) return "Take Flight";
			else return "Take Flight (yellow)";
		case "056": if ($showPitch == false) return "Take Flight";
			else return "Take Flight (blue)";
		case "057": if ($showPitch == false) return "Courageous Steelhand";
			else return "Courageous Steelhand (red)";
		case "058": if ($showPitch == false) return "Courageous Steelhand";
			else return "Courageous Steelhand (yellow)";
		case "059": if ($showPitch == false) return "Courageous Steelhand";
			else return "Courageous Steelhand (blue)";
		case "060": return "Vestige of Sol";
		case "061": return "Halo of lllumination";
		case "062": if ($showPitch == false) return "Celestial Cataclysm";
			else return "Celestial Cataclysm (yellow)";
		case "063": if ($showPitch == false) return "Soul Shield";
			else return "Soul Shield (yellow)";
		case "064": if ($showPitch == false) return "Soul Food";
			else return "Soul Food (yellow)";
		case "065": if ($showPitch == false) return "Tome of Divinity";
			else return "Tome of Divinity (yellow)";
		case "066": if ($showPitch == false) return "Invigorating Light";
			else return "Invigorating Light (red)";
		case "067": if ($showPitch == false) return "Invigorating Light";
			else return "Invigorating Light (yellow)";
		case "068": if ($showPitch == false) return "Invigorating Light";
			else return "Invigorating Light (blue)";
		case "069": if ($showPitch == false) return "Glisten";
			else return "Glisten (red)";
		case "070": if ($showPitch == false) return "Glisten";
			else return "Glisten (yellow)";
		case "071": if ($showPitch == false) return "Glisten";
			else return "Glisten (blue)";
		case "072": if ($showPitch == false) return "Illuminate";
			else return "Illuminate (red)";
		case "073": if ($showPitch == false) return "Illuminate";
			else return "Illuminate (yellow)";
		case "074": if ($showPitch == false) return "Illuminate";
			else return "Illuminate (blue)";
		case "075": if ($showPitch == false) return "Impenetrable Belief";
			else return "Impenetrable Belief (red)";
		case "076": if ($showPitch == false) return "Impenetrable Belief";
			else return "Impenetrable Belief (yellow)";
		case "077": if ($showPitch == false) return "Impenetrable Belief";
			else return "Impenetrable Belief (blue)";
		case "078": if ($showPitch == false) return "Rising Solartide";
			else return "Rising Solartide (red)";
		case "079": if ($showPitch == false) return "Rising Solartide";
			else return "Rising Solartide (yellow)";
		case "080": if ($showPitch == false) return "Rising Solartide";
			else return "Rising Solartide (blue)";
		case "081": if ($showPitch == false) return "Seek Enlightenment";
			else return "Seek Enlightenment (red)";
		case "082": if ($showPitch == false) return "Seek Enlightenment";
			else return "Seek Enlightenment (yellow)";
		case "083": if ($showPitch == false) return "Seek Enlightenment";
			else return "Seek Enlightenment (blue)";
		case "084": if ($showPitch == false) return "Blinding Beam";
			else return "Blinding Beam (red)";
		case "085": if ($showPitch == false) return "Blinding Beam";
			else return "Blinding Beam (yellow)";
		case "086": if ($showPitch == false) return "Blinding Beam";
			else return "Blinding Beam (blue)";
		case "087": if ($showPitch == false) return "Ray of Hope";
			else return "Ray of Hope (yellow)";
		case "088": return "Iris of Reality";
		case "089": return "Phantasmal Footsteps";

		   }	}
if ($set == "fil")
	{  switch($num)	   {

		case "ename": if ($showPitch == false) return "titl";
			else return "titl (pitch)";

		   }	}

        return "";    }
             

function cardID ($cardName)
{
	switch($cardName){
  

		 case "Eye of Ophidia": return array("ARC000");
		 case "Dash, Inventor Extraordinaire": return array("ARC001","CRU098");
		 case "Dash": return array("ARC002");
		 case "‘Teklo Plasma Pistol": return array("ARC003");
		 case "Teklo Foundry Heart": return array("ARC004");
		 case "Achilles Accelerator": return array("ARC005");
		 case "High Octane": return array("ARC006");
		 case "Teklo Core": return array("ARC007");
		 case "Maximum Velocity": return array("ARC008");
		 case "Spark of Genius": return array("ARC009");
		 case "Induction Chamber": return array("ARC010");
		 case "Pedal to the Metal": return array("ARC011","ARC012","ARC013");
		 case "Pour the Mold": return array("ARC014","ARC015","ARC016");
		 case "Aether Sink": return array("ARC017");
		 case "Cognition Nodes": return array("ARC018");
		 case "Convection Amplifier": return array("ARC019");
		 case "Qver Loop": return array("ARC020","ARC021","ARC022");
		 case "Throttle": return array("ARC023","ARC024","ARC025");
		 case "Zero to Sixty": return array("ARC026","ARC027","ARC028");
		 case "Zipper Hit": return array("ARC029","ARC030","ARC031");
		 case "Locked and Loaded": return array("ARC032","ARC033","ARC034");
		 case "Dissipation Shield": return array("ARC035");
		 case "Hyper Driver": return array("ARC036");
		 case "Optekal Monocle": return array("ARC037");
		 case "Azalea, Ace in the Hole": return array("ARC038");
		 case "£ Azalea o": return array("ARC039");
		 case "Death Dealer": return array("ARC040","CRU120");
		 case "Skullbone Crosswrap": return array("ARC041");
		 case "Bull's Eye Bracers": return array("ARC042");
		 case "Red in the Ledger": return array("ARC043");
		 case "Three of a Kind": return array("ARC044");
		 case "Endless Arrow": return array("ARC045");
		 case "Nock the Deathwhistle": return array("ARC046");
		 case "Rapid Fire": return array("ARC047");
		 case "Take Cover": return array("ARC048","ARC049","ARC050");
		 case "Silver the Tip": return array("ARC051","ARC052","ARC053");
		 case "Take Aim": return array("ARC054","ARC055","ARC056");
		 case "Head Shot": return array("ARC057","ARC058","ARC059");
		 case "Hamstring Shot": return array("ARC060","ARC061","ARC062");
		 case "Ridge Rider Shot": return array("ARC063","ARC064","ARC065");
		 case "Salvage Shot": return array("ARC066","ARC067","ARC068");
		 case "Searing Shot": return array("ARC069","ARC070","ARC071");
		 case "Sic 'Em Shot": return array("ARC072","ARC073","ARC074");
		 case "Viserai, Rune Blood": return array("ARC075","CRU138");
		 case "Viserai": return array("ARC076");
		 case "Nebula Blade": return array("ARC077","CRU139");
		 case "Grasp of the Arknight": return array("ARC078");
		 case "Crown of Dichotomy": return array("ARC079");
		 case "Arknight Ascendancy": return array("ARC080");
		 case "Mordred Tide": return array("ARC081");
		 case "Ninth Blade of the Blood Oatt": return array("ARC082");
		 case "Become the Arknight": return array("ARC083");
		 case "Tome of the Arknight": return array("ARC084");
		 case "Spellblade Assault": return array("ARC085","ARC086","ARC087");
		 case "Reduce to Runechant": return array("ARC088","ARC089","ARC090");
		 case "Qath of the Arknight": return array("ARC091","ARC092","ARC093");
		 case "Amplify the Arknight": return array("ARC094","ARC095","ARC096");
		 case "Drawn to the Dark Dimension": return array("ARC097","ARC098","ARC099");
		 case "Rune Flash": return array("ARC100","ARC101","ARC102");
		 case "Spellblade Strike": return array("ARC103","ARC104","ARC105");
		 case "Bloodspill Invocation": return array("ARC106","ARC107","ARC108");
		 case "Read the Runes": return array("ARC109","ARC110","ARC111");
		 case "Runechant": return array("ARC112","CRU157");
		 case "Cano, Dracai of Aether": return array("ARC113","CRU158");
		 case "Kano": return array("ARC114");
		 case "rucible of Aetherweav": return array("ARC115");
		 case "Storm Striders": return array("ARC116");
		 case "Robe of Rapture": return array("ARC117");
		 case "~ Blazing Aether": return array("ARC118");
		 case "Sonic Boom": return array("ARC119");
		 case "Forked Lightning": return array("ARC120");
		 case "Lesson in Lava": return array("ARC121");
		 case "Tome of Aetherwind": return array("ARC122");
		 case "Absorb in Aether": return array("ARC123","ARC124","ARC125");
		 case "Aether Spindle": return array("ARC126","ARC127","ARC128");
		 case "Stir the Aetherwinds": return array("ARC129","ARC130","ARC131");
		 case "Aether Flare": return array("ARC132","ARC133","ARC134");
		 case "Index": return array("ARC135","ARC136","ARC137");
		 case "Reverberate": return array("ARC138","ARC139","ARC140");
		 case "Scalding Rain": return array("ARC141","ARC142","ARC143");
		 case "Zap": return array("ARC144","ARC145","ARC146");
		 case "Voltic Bolt": return array("ARC147","ARC148","ARC149");
		 case "Arcanite Skullcap": return array("ARC150");
		 case "Talismanic Lens": return array("ARC151");
		 case "Vest of the First Fist": return array("ARC152");
		 case "Bracers of Beliet": return array("ARC153");
		 case "Mage Master Boots": return array("ARC154");
		 case "Nullrune Hood": return array("ARC155");
		 case "Nullrune Robe": return array("ARC156");
		 case "Nullrune Gloves": return array("ARC157");
		 case "Nullrune Boots": return array("ARC158");
		 case "Command and Conquer": return array("ARC159");
		 case "Art of War": return array("ARC160");
		 case "Pursuit of Knowledge": return array("ARC161");
		 case "Chains of Eminence": return array("ARC162");
		 case "Rusted Relic": return array("ARC163");
		 case "Life for a Life": return array("ARC164","ARC165","ARC166");
		 case "Enchanting Melody": return array("ARC167","ARC168","ARC169");
		 case "Plunder Run": return array("ARC170","ARC171","ARC172");
		 case "Eirina's Prayer": return array("ARC173","ARC174","ARC175");
		 case "Back Alley Breakline": return array("ARC176","ARC177","ARC178");
		 case "Cadaverous Contraband": return array("ARC179","ARC180","ARC181");
		 case "Fervent Forerunner": return array("ARC182","ARC183","ARC184");
		 case "Moon Wish": return array("ARC185","ARC186","ARC187");
		 case "Push the Point": return array("ARC188","ARC189","ARC190");
		 case "Ravenous Rabble": return array("ARC191","ARC192","ARC193");
		 case "Rifting": return array("ARC194","ARC195","ARC196");
		 case "Vigor Rush": return array("ARC197","ARC198","ARC199");
		 case "Fate Foreseen": return array("ARC200","ARC201","ARC202");
		 case "Come to Fight": return array("ARC203","ARC204","ARC205");
		 case "Force Sight": return array("ARC206","ARC207","ARC208");
		 case "Lead the Charge": return array("ARC209","ARC210","ARC211");
		 case "Sun Kiss": return array("ARC212","ARC213","ARC214");
		 case "Whisper of the Oracle": return array("ARC215","ARC216","ARC217");
		 case "Cracked Bauble": return array("ARC218","CRU195","ELE237");
		 case "Arknight Shard": return array("CRU000");
		 case "vinar, Reckless Rampa;": return array("CRU001");
		 case "Kayo, Berserker Runt": return array("CRU002");
		 case "Romping Club": return array("CRU003");
		 case "Mandible Claw": return array("CRU004","CRU005");
		 case "Skullhorn": return array("CRU006");
		 case "Beast Within": return array("CRU007");
		 case "Massacre": return array("CRU008");
		 case "Argh... Smash!": return array("CRU009");
		 case "Barraging Big Horn": return array("CRU010","CRU011","CRU012");
		 case "Predatory Assault": return array("CRU013","CRU014","CRU015");
		 case "Riled Up": return array("CRU016","CRU017","CRU018");
		 case "Swing Fist, Think Later": return array("CRU019","CRU020","CRU021");
		 case "Bravo, Showstopper": return array("CRU022");
		 case "Anothos": return array("CRU023");
		 case "Sledge of Anvilheim": return array("CRU024");
		 case "Crater Fist": return array("CRU025");
		 case "Mangle": return array("CRU026");
		 case "Righteous Cleansing": return array("CRU027");
		 case "Stamp Authority": return array("CRU028");
		 case "Towering Titan": return array("CRU029","CRU030","CRU031");
		 case "Crush the Weak": return array("CRU032","CRU033","CRU034");
		 case "Chokeslam": return array("CRU035","CRU036","CRU037");
		 case "Emerging Dominance": return array("CRU038","CRU039","CRU040");
		 case "Blessing of Serenity": return array("CRU041","CRU042","CRU043");
		 case "Seismic Surge": return array("CRU044","ELE212");
		 case "Katsu, the Wanderer": return array("CRU045");
		 case "Ira, Crimson Haze": return array("CRU046");
		 case "enji, the Piercing Win": return array("CRU047");
		 case "Harmonized Kodachi": return array("CRU048","CRU049");
		 case "Edge of Autumn": return array("CRU050");
		 case "Zephyr Needle": return array("CRU051","CRU052");
		 case "Breeze Rider Boots": return array("CRU053");
		 case "Find Center": return array("CRU054");
		 case "Flood of Force": return array("CRU055");
		 case "Heron's Flight": return array("CRU056");
		 case "Crane Dance": return array("CRU057","CRU058","CRU059");
		 case "Rushing River": return array("CRU060","CRU061","CRU062");
		 case "Flying Kick": return array("CRU063","CRU064","CRU065");
		 case "Soulbead Strike": return array("CRU066","CRU067","CRU068");
		 case "Torrent of Tempo": return array("CRU069","CRU070","CRU071");
		 case "Bittering Thorns": return array("CRU072");
		 case "Salt the Wound": return array("CRU073");
		 case "Whirling Mist Blossom": return array("CRU074");
		 case "Zen State": return array("CRU075");
		 case "Dorinthea Ironsong": return array("CRU076");
		 case "assai, Cintari Sellswor": return array("CRU077");
		 case "Dawnblade": return array("CRU078");
		 case "Cintari Saber": return array("CRU079","CRU080");
		 case "Courage of Bladehold": return array("CRU081");
		 case "Twinning Blade": return array("CRU082");
		 case "Unified Decree": return array("CRU083");
		 case "Spoils of War": return array("CRU084");
		 case "Dauntless": return array("CRU085","CRU086","CRU087");
		 case "Out for Blood": return array("CRU088","CRU089","CRU090");
		 case "Hit and Run": return array("CRU091","CRU092","CRU093");
		 case "Push Forward": return array("CRU094","CRU095","CRU096");
		 case "riyana, Diamond Gemi": return array("CRU097");
		 case "Data Doll MKII": return array("CRU099");
		 case "Teklo Plasma Pistol": return array("CRU100");
		 case "Plasma Barrel Shot": return array("CRU101");
		 case "Viziertronic Model i": return array("CRU102");
		 case "Meganetic Shockwave": return array("CRU103");
		 case "Absorption Dome": return array("CRU104");
		 case "Plasma Purifier": return array("CRU105");
		 case "High Speed Impact": return array("CRU106","CRU107","CRU108");
		 case "Combustible Courier": return array("CRU109","CRU110","CRU111");
		 case "Overblast": return array("CRU112","CRU113","CRU114");
		 case "Teklovossen's Workshop": return array("CRU115","CRU116","CRU117");
		 case ";Kavdaen, Trader of Skiy}s/": return array("CRU118");
		 case ":Azalea, Ace in the qug": return array("CRU119");
		 case "Red Liner": return array("CRU121");
		 case "Perch Grapplers": return array("CRU122");
		 case "Remorseless": return array("CRU123");
		 case "Poison the Tips": return array("CRU124");
		 case "Feign Death": return array("CRU125");
		 case "Tripwire Trap": return array("CRU126");
		 case "Pitfall Trap": return array("CRU127");
		 case "Rockslide Trap": return array("CRU128");
		 case "Pathing Helix": return array("CRU129","CRU130","CRU131");
		 case "Sleep Dart": return array("CRU132","CRU133","CRU134");
		 case "Increase the Tension": return array("CRU135","CRU136","CRU137");
		 case "Reaping Blade": return array("CRU140");
		 case "Bloodsheath Skeleta": return array("CRU141");
		 case "Dread Triptych": return array("CRU142");
		 case "Rattle Bones": return array("CRU143");
		 case "Runeblood Barrier": return array("CRU144");
		 case "Mauvrion Skies": return array("CRU145","CRU146","CRU147");
		 case "Consuming Volition": return array("CRU148","CRU149","CRU150");
		 case "Meat and Greet": return array("CRU151","CRU152","CRU153");
		 case "Sutcliffe's Research Notes": return array("CRU154","CRU155","CRU156");
		 case "rucible of Aetherweay": return array("CRU159");
		 case "Aether Conduit": return array("CRU160");
		 case "Metacarpus Node": return array("CRU161");
		 case "Chain Lightning": return array("CRU162");
		 case "Gaze the Ages": return array("CRU163");
		 case "Aetherize": return array("CRU164");
		 case "Cindering Foresight": return array("CRU165","CRU166","CRU167");
		 case "Foreboding Bolt": return array("CRU168","CRU169","CRU170");
		 case "Rousing Aether": return array("CRU171","CRU172","CRU173");
		 case "Snapback": return array("CRU174","CRU175","CRU176");
		 case "alishar, the Lost Princ": return array("CRU177");
		 case "Fyendal's Spring Tunic": return array("CRU178");
		 case "Gambler's Gloves": return array("CRU179");
		 case "Coax a Commotion": return array("CRU180");
		 case "Gorganian Tome": return array("CRU181");
		 case "Shag": return array("CRU182");
		 case "Promise of Plenty": return array("CRU183","CRU184","CRU185");
		 case "Lunging Press": return array("CRU186");
		 case "Springboard Somersault": return array("CRU187");
		 case "Cash In": return array("CRU188");
		 case "Reinforce the Line": return array("CRU189","CRU190","CRU191");
		 case "Brutal Assault": return array("CRU192","CRU193","CRU194");
		 case "Quicken": return array("CRU196");
		 case "Copper": return array("CRU197");
		 case "Korshem, Crossroad of Element": return array("ELE000");
		 case "him, Grandfather of Eter": return array("ELE001");
		 case "Oldhim": return array("ELE002");
		 case "Winter's Wail": return array("ELE003");
		 case "Endless Winter": return array("ELE004");
		 case "Qaken Old": return array("ELE005");
		 case "Awakening": return array("ELE006");
		 case "Biting Gale": return array("ELE007","ELE008","ELE009");
		 case "Turn Timber": return array("ELE010","ELE011","ELE012");
		 case "Entangle": return array("ELE013","ELE014","ELE015");
		 case "Glacial Footsteps": return array("ELE016","ELE017","ELE018");
		 case "Mulch": return array("ELE019","ELE020","ELE021");
		 case "Snow Under": return array("ELE022","ELE023","ELE024");
		 case "Emerging Avalanche": return array("ELE025","ELE026","ELE027");
		 case "Strength of Sequoia": return array("ELE028","ELE029","ELE030");
		 case "Lexi, Livewire": return array("ELE031");
		 case "Lexi": return array("ELE032");
		 case "Shiver": return array("ELE033");
		 case "Voltaire, Strike Twice": return array("ELE034");
		 case "Frost Lock": return array("ELE035");
		 case "Light it Up": return array("ELE036");
		 case "lIce Storm": return array("ELE037");
		 case "Cold Wave": return array("ELE038","ELE039","ELE040");
		 case "Snap Shot": return array("ELE041","ELE042","ELE043");
		 case "Blizzard Bolt": return array("ELE044","ELE045","ELE046");
		 case "Buzz Bolt": return array("ELE047","ELE048","ELE049");
		 case "Chilling Icevein": return array("ELE050","ELE051","ELE052");
		 case "Dazzling Crescendo": return array("ELE053","ELE054","ELE055");
		 case "Flake Out": return array("ELE056","ELE057","ELE058");
		 case "Frazzle": return array("ELE059","ELE060","ELE061");
		 case "riar, Warden of Thorn": return array("ELE062");
		 case "Briar": return array("ELE063");
		 case "Blossoming Spellblade": return array("ELE064");
		 case "Flicker Wisp": return array("ELE065");
		 case "Force of Nature": return array("ELE066");
		 case "Explosive Growth": return array("ELE067","ELE068","ELE069");
		 case "Rites of Lightning": return array("ELE070","ELE071","ELE072");
		 case "Arcanic Shockwave": return array("ELE073","ELE074","ELE075");
		 case "Vela Flash": return array("ELE076","ELE077","ELE078");
		 case "Rites of Replenishment": return array("ELE079","ELE080","ELE081");
		 case "Stir the Wildwood": return array("ELE082","ELE083","ELE084");
		 case "Bramble Spark": return array("ELE085","ELE086","ELE087");
		 case "Inspire Lightning": return array("ELE088","ELE089","ELE090");
		 case "Fulminate": return array("ELE091");
		 case "Flashfreeze": return array("ELE092");
		 case "Exposed to the Elements": return array("ELE093");
		 case "Entwine Earth": return array("ELE094","ELE095","ELE096");
		 case "Entwine lce": return array("ELE097","ELE098","ELE099");
		 case "Entwine Lightning": return array("ELE100","ELE101","ELE102");
		 case "Invigorate": return array("ELE103","ELE104","ELE105");
		 case "Rejuvenate": return array("ELE106","ELE107","ELE108");
		 case "Embodiment of Earth": return array("ELE109");
		 case "mbodiment of Lightnin": return array("ELE110");
		 case "Frostbite": return array("ELE111");
		 case "Pulse of Volthaven": return array("ELE112");
		 case "Pulse of Candlehold": return array("ELE113");
		 case "Pulse of Isenloft": return array("ELE114");
		 case "Crown of Seeds": return array("ELE115");
		 case "Plume of Evergrowth": return array("ELE116");
		 case "Channel Mount Heroic": return array("ELE117");
		 case "Tome of Harvests": return array("ELE118");
		 case "Evergreen": return array("ELE119","ELE120","ELE121");
		 case "Weave Earth": return array("ELE122","ELE123","ELE124");
		 case "Summerwood Shelter": return array("ELE125","ELE126","ELE127");
		 case "Autumn's Touch": return array("ELE128","ELE129","ELE130");
		 case "Break Ground": return array("ELE131","ELE132","ELE133");
		 case "Burgeoning": return array("ELE134","ELE135","ELE136");
		 case "Earthlore Surge": return array("ELE137","ELE138","ELE139");
		 case "Sow Tomorrow": return array("ELE140","ELE141","ELE142");
		 case "Amulet of Earth": return array("ELE143");
		 case "Heart of Ice": return array("ELE144");
		 case "Coat of Frost": return array("ELE145");
		 case "Channel Lake Frigid": return array("ELE146");
		 case "Blizzard": return array("ELE147");
		 case "Frost Fang": return array("ELE148","ELE149","ELE150");
		 case "Ice Quake": return array("ELE151","ELE152","ELE153");
		 case "Weave Ice": return array("ELE154","ELE155","ELE156");
		 case "Icy Encounter": return array("ELE157","ELE158","ELE159");
		 case "Winter's Grasp": return array("ELE160","ELE161","ELE162");
		 case "Chill to the Bone": return array("ELE163","ELE164","ELE165");
		 case "Polar Blast": return array("ELE166","ELE167","ELE168");
		 case "Winter's Bite": return array("ELE169","ELE170","ELE171");
		 case "Amulet of Ice": return array("ELE172");
		 case "Shock Charmers": return array("ELE173");
		 case "Mark of Lightning": return array("ELE174");
		 case "Channel Thunder Steppe": return array("ELE175");
		 case "Blink": return array("ELE176");
		 case "Flash": return array("ELE177","ELE178","ELE179");
		 case "Weave Lightning": return array("ELE180","ELE181","ELE182");
		 case "Lightning Press": return array("ELE183","ELE184","ELE185");
		 case "Ball Lightning": return array("ELE186","ELE187","ELE188");
		 case "Lightning Surge": return array("ELE189","ELE190","ELE191");
		 case "Heaven's Claws": return array("ELE192","ELE193","ELE194");
		 case "Shock Striker": return array("ELE195","ELE196","ELE197");
		 case "Electrify": return array("ELE198","ELE199","ELE200");
		 case "Amulet of Lightning": return array("ELE201");
		 case "Titan's Fist": return array("ELE202");
		 case "mpart of the Ram's He": return array("ELE203");
		 case "Rotten Old Buckler": return array("ELE204");
		 case "Tear Asunder": return array("ELE205");
		 case "Embolden": return array("ELE206","ELE207","ELE208");
		 case "Thump": return array("ELE209","ELE210","ELE211");
		 case "New Horizon": return array("ELE213");
		 case "Honing Hood": return array("ELE214");
		 case "Seek and Destroy": return array("ELE215");
		 case "Bolt'n' Shot": return array("ELE216","ELE217","ELE218");
		 case "Over Flex": return array("ELE219","ELE220","ELE221");
		 case "Rosetta Thorn": return array("ELE222");
		 case "Duskblade": return array("ELE223");
		 case "Spellbound Creepers": return array("ELE224");
		 case "Sutcliffe’'s Suede Hides": return array("ELE225");
		 case "Sting of Sorcery": return array("ELE226");
		 case "Sigil of Suffering": return array("ELE227","ELE228","ELE229");
		 case "Singeing Steelblade": return array("ELE230","ELE231","ELE232");
		 case "Ragamufhin's Hat": return array("ELE233");
		 case "Deep Blue": return array("ELE234");
		 case "Cracker Jax": return array("ELE235");
		 case "Runaways": return array("ELE236");
		 case "The Great Library of Solan": return array("MON000");
		 case "sm, Sculptor of Arc Li": return array("MON001");
		 case "Prism": return array("MON002");
		 case "Luminaris": return array("MON003");
		 case "Herald of Erudition": return array("MON004");
		 case "Arc Light Sentinel": return array("MON005");
		 case "Genesis": return array("MON006");
		 case "Herald of Judgment": return array("MON007");
		 case "Herald of Triumph": return array("MON008","MON009","MON010");
		 case "Parable of Humility": return array("MON011");
		 case "Merciful Retribution": return array("MON012");
		 case "Qde to Wrath": return array("MON013");
		 case "Herald of Protection": return array("MON014","MON015","MON016");
		 case "Herald of Ravages": return array("MON017","MON018","MON019");
		 case "Herald of Rebirth": return array("MON020","MON021","MON022");
		 case "Herald of Tenacity": return array("MON023","MON024","MON025");
		 case "Wartune Herald": return array("MON026","MON027","MON028");
		 case "Boltyn, Breaker of D:": return array("MON029");
		 case "Boltyn": return array("MON030");
		 case "Raydn, Duskbane": return array("MON031");
		 case "Bolting Blade": return array("MON032");
		 case "Beacon of Victory": return array("MON033");
		 case "Lumina Ascension": return array("MON034");
		 case "V of the Vanguard": return array("MON035");
		 case "Battlefield Blitz": return array("MON036","MON037","MON038");
		 case "Valiant Thrust": return array("MON039","MON040","MON041");
		 case "Bolt of Courage": return array("MON042","MON043","MON044");
		 case "Cross the Line": return array("MON045","MON046","MON047");
		 case "Engulfing Light": return array("MON048","MON049","MON050");
		 case "Express Lightning": return array("MON051","MON052","MON053");
		 case "Take Flight": return array("MON054","MON055","MON056");
		 case "Courageous Steelhand": return array("MON057","MON058","MON059");
		 case "Vestige of Sol": return array("MON060");
		 case "Halo of lllumination": return array("MON061");
		 case "Celestial Cataclysm": return array("MON062");
		 case "Soul Shield": return array("MON063");
		 case "Soul Food": return array("MON064");
		 case "Tome of Divinity": return array("MON065");
		 case "Invigorating Light": return array("MON066","MON067","MON068");
		 case "Glisten": return array("MON069","MON070","MON071");
		 case "Illuminate": return array("MON072","MON073","MON074");
		 case "Impenetrable Belief": return array("MON075","MON076","MON077");
		 case "Rising Solartide": return array("MON078","MON079","MON080");
		 case "Seek Enlightenment": return array("MON081","MON082","MON083");
		 case "Blinding Beam": return array("MON084","MON085","MON086");
		 case "Ray of Hope": return array("MON087");
		 case "Iris of Reality": return array("MON088");
		 case "Phantasmal Footsteps": return array("MON089");
		 case "titl": return array("filename");


		}

	 return array(); }

?>

